// AUTO-GENERATED by scripts/generate-skill-graph.mjs
// Do NOT edit by hand. Re-run after modifying any SKILL.md.
// Generated: 2026-05-18T14:17:32.472Z

export interface GraphNode {
  id: string;
  inDegree: number;
  outDegree: number;
}

export interface GraphEdge {
  source: string;
  target: string;
  weight: number;
}

export const NODES: readonly GraphNode[] = [
  {
    "id": "abandoned-cart-recovery",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "action-bias-coach",
    "inDegree": 4,
    "outDegree": 1
  },
  {
    "id": "agent-disagreement-resolver",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "agent-handoff",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "agent-self-debug",
    "inDegree": 2,
    "outDegree": 4
  },
  {
    "id": "agent-self-time-budget",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "always-on-poller",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "apple-watch-complication",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "appointment-availability-publisher",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "appointment-booking-engine",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "appointment-no-show-recovery",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "appointment-recurring-rebooker",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "appointment-reminder-sequencer",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "approval-card-builder",
    "inDegree": 14,
    "outDegree": 0
  },
  {
    "id": "approval-expiry-sweeper",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "approval-revisit-detector",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "audit-log-generator",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "auto-approval-audit",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "auto-approve-low-risk",
    "inDegree": 1,
    "outDegree": 5
  },
  {
    "id": "auto-archive-spam",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "autonomous-health-check",
    "inDegree": 3,
    "outDegree": 2
  },
  {
    "id": "backup-verifier",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "batch-post-scheduler",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "batching-quiet-hours",
    "inDegree": 4,
    "outDegree": 2
  },
  {
    "id": "blog-draft-writer",
    "inDegree": 4,
    "outDegree": 3
  },
  {
    "id": "blog-post-generator",
    "inDegree": 2,
    "outDegree": 7
  },
  {
    "id": "brand-extractor",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "broken-link-finder",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "browser-driven-vendor-setup",
    "inDegree": 4,
    "outDegree": 0
  },
  {
    "id": "calendar-context-pull",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "case-study-from-customer",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "case-study-writer",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "chargeback-disputer",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "chatbot-prompt-builder",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "chemistry-reading-parser",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "churn-risk-scorer",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "cohort-retention-tracker",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "comment-engagement-tracker",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "complaint-escalation",
    "inDegree": 5,
    "outDegree": 4
  },
  {
    "id": "confidence-and-gate-statement",
    "inDegree": 2,
    "outDegree": 2
  },
  {
    "id": "content-calendar-orchestrator",
    "inDegree": 6,
    "outDegree": 2
  },
  {
    "id": "copy-writer",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "council-advisor-tuner",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "council-decision",
    "inDegree": 5,
    "outDegree": 1
  },
  {
    "id": "council-decision-followup-tracker",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "council-question-quality-check",
    "inDegree": 2,
    "outDegree": 2
  },
  {
    "id": "cross-business-content-calendar",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "cross-business-prioritizer",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "customer-build-day-1-bootstrap",
    "inDegree": 5,
    "outDegree": 6
  },
  {
    "id": "customer-data-deletion-handler",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "customer-history-lookup",
    "inDegree": 4,
    "outDegree": 3
  },
  {
    "id": "customer-ltv-calculator",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "customer-readiness-check",
    "inDegree": 6,
    "outDegree": 1
  },
  {
    "id": "customer-service-triage",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "customer-visit-note-writer",
    "inDegree": 3,
    "outDegree": 1
  },
  {
    "id": "customer-voice-mapper",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "daily-eod",
    "inDegree": 8,
    "outDegree": 0
  },
  {
    "id": "daily-kickoff",
    "inDegree": 18,
    "outDegree": 0
  },
  {
    "id": "daily-kickoff-telegram-formatter",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "data-retention-pruner",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "day14-voice",
    "inDegree": 24,
    "outDegree": 0
  },
  {
    "id": "decision-fatigue-detector",
    "inDegree": 1,
    "outDegree": 3
  },
  {
    "id": "defer-vs-do-decider",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "deploy-smoke-tester",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "discount-floor-enforcer",
    "inDegree": 2,
    "outDegree": 2
  },
  {
    "id": "dispatch-day-of-reshuffler",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "dispatch-eta-publisher",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "dispatch-route-optimizer",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "dispatch-tech-tracker",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "dm-follow-up-detector",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "dm-reply-classifier",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "dns-drift-watcher",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "dns-records-writer",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "dossier-folder-initializer",
    "inDegree": 6,
    "outDegree": 2
  },
  {
    "id": "draft-promoter",
    "inDegree": 1,
    "outDegree": 7
  },
  {
    "id": "dunning-email-sequencer",
    "inDegree": 3,
    "outDegree": 3
  },
  {
    "id": "ecom-stripe-payment-link-setup",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "email-fallback-channel",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "email-newsletter-composer",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "emergent-skill-graduator",
    "inDegree": 3,
    "outDegree": 5
  },
  {
    "id": "energy-state-tracker",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "eod-telegram-formatter",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "eod-update-writer",
    "inDegree": 12,
    "outDegree": 1
  },
  {
    "id": "error-recovery-resume",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "escalation-pattern-detector",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "etsy-listing-writer",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "etsy-pricing-validator",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "etsy-product-mockup-prompts",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "etsy-shop-policies-generator",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "etsy-tag-researcher",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "evacuation-zone-mapper",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "event-rollup-summarizer",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "event-to-telegram-mapper",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "failed-payment-retry",
    "inDegree": 2,
    "outDegree": 1
  },
  {
    "id": "feedback-classifier",
    "inDegree": 2,
    "outDegree": 4
  },
  {
    "id": "focus-block-protector",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "followup-action-creator",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "gap-moment-logger",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "gdpr-data-export",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "git-fork-utility",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "growth-always-on",
    "inDegree": 2,
    "outDegree": 2
  },
  {
    "id": "growth-cluster-gap-detector",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "growth-metrics-dashboard",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "growth-skill-spec-generator",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "hurricane-watch-poller",
    "inDegree": 3,
    "outDegree": 1
  },
  {
    "id": "idempotent-bash-script",
    "inDegree": 2,
    "outDegree": 0
  },
  {
    "id": "image-generator",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "inbound-classifier",
    "inDegree": 16,
    "outDegree": 0
  },
  {
    "id": "incremental-scope-commit",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "instagram-reel-caption-writer",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "intake-nudge-writer",
    "inDegree": 2,
    "outDegree": 0
  },
  {
    "id": "intake-parser",
    "inDegree": 4,
    "outDegree": 1
  },
  {
    "id": "internal-link-suggester",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "inventory-tracker",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "jack-asleep-detector",
    "inDegree": 3,
    "outDegree": 3
  },
  {
    "id": "jack-language-decoder",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "kickoff-call-scheduler",
    "inDegree": 5,
    "outDegree": 2
  },
  {
    "id": "launch-agent-setup",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "launch-day-customer-email",
    "inDegree": 3,
    "outDegree": 3
  },
  {
    "id": "launch-day-cutover",
    "inDegree": 9,
    "outDegree": 2
  },
  {
    "id": "lead-first-touch-personalizer",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "lead-source-tracker",
    "inDegree": 1,
    "outDegree": 5
  },
  {
    "id": "leaked-secret-cleanup",
    "inDegree": 4,
    "outDegree": 0
  },
  {
    "id": "lighthouse-runner",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "linkedin-thought-leadership-post",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "local-event-detector",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "log-anomaly-detector",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "meta-growth-watcher",
    "inDegree": 2,
    "outDegree": 1
  },
  {
    "id": "morning-briefing-generator",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "morning-headline-format",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "mrr-calculator",
    "inDegree": 2,
    "outDegree": 2
  },
  {
    "id": "multi-command-parser",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "multi-tenant-mrr-aggregator",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "next-app-router-conventions",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "nightly-polish",
    "inDegree": 6,
    "outDegree": 0
  },
  {
    "id": "nightly-polish-alert",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "no-edge-in-memory-state",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "no-hardcoded-tz-offset",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "no-string-prefix-encoding",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "numbered-decision-rationale",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "og-image-generator",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "order-fulfillment-orchestrator",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "outreach-trigger",
    "inDegree": 4,
    "outDegree": 1
  },
  {
    "id": "parallel-task-fanout-author",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "pattern-recurrence-detector",
    "inDegree": 6,
    "outDegree": 1
  },
  {
    "id": "payment-receipt-customizer",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "per-tenant-daily-rollup",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "performance-regression-detector",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "phase-numbered-cross-reference",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "photo-proof-archive",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "photo-proof-customer-portal",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "photo-proof-uploader",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "photo-proof-watermarker",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "photo-watermarker",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "pipeline-end-to-end-test",
    "inDegree": 0,
    "outDegree": 4
  },
  {
    "id": "pipeline-stuckness-detector",
    "inDegree": 0,
    "outDegree": 4
  },
  {
    "id": "pod-design-brief-generator",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "pod-niche-researcher",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "pod-product-mix-recommender",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "post-storm-damage-assessor",
    "inDegree": 0,
    "outDegree": 4
  },
  {
    "id": "postmortem-writer",
    "inDegree": 5,
    "outDegree": 5
  },
  {
    "id": "power-outage-detector",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "pre-flight-verification-pass",
    "inDegree": 3,
    "outDegree": 1
  },
  {
    "id": "prevention-skill-suggester",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "pricing-decision-helper",
    "inDegree": 3,
    "outDegree": 2
  },
  {
    "id": "pricing-margin-calculator",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "printify-product-creator",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "priority-ranker",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "privacy-policy-keeper",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "proactive-monitor",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "product-catalog-manager",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "product-photo-organizer",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "project-change-order-handler",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "project-completion-walkthrough",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "project-deposit-balance-billing",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "project-gantt-renderer",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "project-milestone-tracker",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "project-photo-stream",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "read-aloud-checker",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "recursive-growth-throttle",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "refund-handler",
    "inDegree": 1,
    "outDegree": 5
  },
  {
    "id": "repo-rename-after-fork",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "returns-handler",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "review-followup-tracker",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "review-monitoring-poller",
    "inDegree": 2,
    "outDegree": 2
  },
  {
    "id": "review-request-sender",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "review-response",
    "inDegree": 6,
    "outDegree": 0
  },
  {
    "id": "review-sentiment-scorer",
    "inDegree": 3,
    "outDegree": 2
  },
  {
    "id": "risk-scoring",
    "inDegree": 2,
    "outDegree": 3
  },
  {
    "id": "root-cause-categorizer",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "scheduled-task-portability-audit",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "scheduled-task-prompt-author",
    "inDegree": 2,
    "outDegree": 1
  },
  {
    "id": "seo-city-page-builder",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "seo-keyword-cluster-builder",
    "inDegree": 1,
    "outDegree": 4
  },
  {
    "id": "seo-keyword-fetcher",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "session-path-hardcode-detector",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "session-recovery",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "shipping-label-generator",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "short-link-router",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "shortcuts-bridge",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "skill-coverage-auditor",
    "inDegree": 4,
    "outDegree": 2
  },
  {
    "id": "skill-deprecation-flagger",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "skill-fire-wrapper",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "skill-gap-detector",
    "inDegree": 2,
    "outDegree": 3
  },
  {
    "id": "skill-invocation-monitor",
    "inDegree": 1,
    "outDegree": 4
  },
  {
    "id": "skill-merge-suggester",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "skill-naming-validator",
    "inDegree": 4,
    "outDegree": 3
  },
  {
    "id": "skill-promotion-criteria",
    "inDegree": 3,
    "outDegree": 4
  },
  {
    "id": "skill-registrar",
    "inDegree": 5,
    "outDegree": 4
  },
  {
    "id": "skill-spec-generator",
    "inDegree": 4,
    "outDegree": 2
  },
  {
    "id": "skill-tree-grower",
    "inDegree": 6,
    "outDegree": 8
  },
  {
    "id": "skill-version-bumper",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "social-analytics-rollup",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "social-cross-post",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "ssl-expiry-watcher",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "ssl-provisioning-verifier",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "stop-and-ship-timer",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "storm-week-comms",
    "inDegree": 4,
    "outDegree": 1
  },
  {
    "id": "stripe-payment-link-creator",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "stripe-test-mode-validator",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "stripe-webhook-verifier",
    "inDegree": 2,
    "outDegree": 2
  },
  {
    "id": "subscription-pause-handler",
    "inDegree": 1,
    "outDegree": 4
  },
  {
    "id": "supabase-event-listener",
    "inDegree": 0,
    "outDegree": 11
  },
  {
    "id": "swfl-context",
    "inDegree": 3,
    "outDegree": 0
  },
  {
    "id": "swfl-vertical-deep-dives",
    "inDegree": 1,
    "outDegree": 4
  },
  {
    "id": "telegram-approval-card",
    "inDegree": 3,
    "outDegree": 4
  },
  {
    "id": "telegram-bridge",
    "inDegree": 1,
    "outDegree": 3
  },
  {
    "id": "telegram-command-router",
    "inDegree": 6,
    "outDegree": 6
  },
  {
    "id": "telegram-conversation-state",
    "inDegree": 1,
    "outDegree": 3
  },
  {
    "id": "telegram-inbound-parser",
    "inDegree": 5,
    "outDegree": 3
  },
  {
    "id": "telegram-outbound-formatter",
    "inDegree": 5,
    "outDegree": 1
  },
  {
    "id": "telegram-status-pusher",
    "inDegree": 6,
    "outDegree": 7
  },
  {
    "id": "template-forker",
    "inDegree": 5,
    "outDegree": 0
  },
  {
    "id": "template-version-tracker",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "template-vs-product-decision",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "tenant-context-switcher",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "thumbnail-generator",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "tiktok-caption-writer",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "tomorrow-plan-extractor",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "topic-idea-generator",
    "inDegree": 3,
    "outDegree": 4
  },
  {
    "id": "twitter-video-poster",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "upgrade-nudge-detector",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "upsell-detection",
    "inDegree": 1,
    "outDegree": 8
  },
  {
    "id": "uptime-monitor",
    "inDegree": 1,
    "outDegree": 3
  },
  {
    "id": "urgency-classifier",
    "inDegree": 3,
    "outDegree": 4
  },
  {
    "id": "vercel-deployer",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "vercel-route-cal-com-webhook",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "vercel-route-intake-webhook",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "vercel-route-resend-inbound",
    "inDegree": 1,
    "outDegree": 1
  },
  {
    "id": "vercel-route-stripe-webhook",
    "inDegree": 0,
    "outDegree": 3
  },
  {
    "id": "vertical-9-16-edit-pipeline",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "video-clipper-ffmpeg",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "view-link-handoff",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "viral-hook-rewriter",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "visit-photo-attacher",
    "inDegree": 1,
    "outDegree": 0
  },
  {
    "id": "voice-drift-detector",
    "inDegree": 4,
    "outDegree": 5
  },
  {
    "id": "voice-message-transcriber",
    "inDegree": 3,
    "outDegree": 3
  },
  {
    "id": "voice-tts-out",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "walk-away-detector",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "warm-dm-personalizer",
    "inDegree": 5,
    "outDegree": 2
  },
  {
    "id": "warmth-calibrator",
    "inDegree": 1,
    "outDegree": 2
  },
  {
    "id": "watchdog-self-restarter",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "weekly-council-review",
    "inDegree": 28,
    "outDegree": 0
  },
  {
    "id": "weekly-priorities-flush",
    "inDegree": 3,
    "outDegree": 1
  },
  {
    "id": "whisper-transcription-captioner",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "win-back-campaign-trigger",
    "inDegree": 1,
    "outDegree": 3
  },
  {
    "id": "yesterday-wins-extractor",
    "inDegree": 0,
    "outDegree": 2
  },
  {
    "id": "youtube-script-from-blog",
    "inDegree": 0,
    "outDegree": 1
  },
  {
    "id": "youtube-shorts-caption-writer",
    "inDegree": 0,
    "outDegree": 0
  },
  {
    "id": "zero-friction-handoff",
    "inDegree": 0,
    "outDegree": 1
  }
];

export const EDGES: readonly GraphEdge[] = [
  {
    "source": "action-bias-coach",
    "target": "council-decision",
    "weight": 2
  },
  {
    "source": "agent-disagreement-resolver",
    "target": "agent-handoff",
    "weight": 2
  },
  {
    "source": "agent-disagreement-resolver",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "agent-disagreement-resolver",
    "target": "action-bias-coach",
    "weight": 1
  },
  {
    "source": "agent-handoff",
    "target": "postmortem-writer",
    "weight": 1
  },
  {
    "source": "agent-self-debug",
    "target": "leaked-secret-cleanup",
    "weight": 2
  },
  {
    "source": "agent-self-debug",
    "target": "browser-driven-vendor-setup",
    "weight": 2
  },
  {
    "source": "agent-self-debug",
    "target": "council-question-quality-check",
    "weight": 2
  },
  {
    "source": "agent-self-debug",
    "target": "action-bias-coach",
    "weight": 2
  },
  {
    "source": "agent-self-time-budget",
    "target": "stop-and-ship-timer",
    "weight": 1
  },
  {
    "source": "agent-self-time-budget",
    "target": "daily-eod",
    "weight": 1
  },
  {
    "source": "always-on-poller",
    "target": "autonomous-health-check",
    "weight": 1
  },
  {
    "source": "always-on-poller",
    "target": "power-outage-detector",
    "weight": 1
  },
  {
    "source": "apple-watch-complication",
    "target": "shortcuts-bridge",
    "weight": 1
  },
  {
    "source": "approval-expiry-sweeper",
    "target": "approval-card-builder",
    "weight": 1
  },
  {
    "source": "approval-revisit-detector",
    "target": "approval-card-builder",
    "weight": 2
  },
  {
    "source": "approval-revisit-detector",
    "target": "weekly-council-review",
    "weight": 2
  },
  {
    "source": "audit-log-generator",
    "target": "data-retention-pruner",
    "weight": 1
  },
  {
    "source": "auto-approve-low-risk",
    "target": "risk-scoring",
    "weight": 1
  },
  {
    "source": "auto-approve-low-risk",
    "target": "customer-build-day-1-bootstrap",
    "weight": 1
  },
  {
    "source": "auto-approve-low-risk",
    "target": "auto-approval-audit",
    "weight": 1
  },
  {
    "source": "auto-approve-low-risk",
    "target": "approval-card-builder",
    "weight": 1
  },
  {
    "source": "auto-approve-low-risk",
    "target": "telegram-approval-card",
    "weight": 1
  },
  {
    "source": "auto-archive-spam",
    "target": "inbound-classifier",
    "weight": 2
  },
  {
    "source": "autonomous-health-check",
    "target": "nightly-polish",
    "weight": 1
  },
  {
    "source": "autonomous-health-check",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "backup-verifier",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "batching-quiet-hours",
    "target": "urgency-classifier",
    "weight": 2
  },
  {
    "source": "batching-quiet-hours",
    "target": "jack-asleep-detector",
    "weight": 2
  },
  {
    "source": "blog-draft-writer",
    "target": "day14-voice",
    "weight": 2
  },
  {
    "source": "blog-draft-writer",
    "target": "swfl-context",
    "weight": 1
  },
  {
    "source": "blog-draft-writer",
    "target": "og-image-generator",
    "weight": 1
  },
  {
    "source": "blog-post-generator",
    "target": "seo-keyword-cluster-builder",
    "weight": 2
  },
  {
    "source": "blog-post-generator",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "blog-post-generator",
    "target": "internal-link-suggester",
    "weight": 2
  },
  {
    "source": "blog-post-generator",
    "target": "voice-drift-detector",
    "weight": 1
  },
  {
    "source": "blog-post-generator",
    "target": "content-calendar-orchestrator",
    "weight": 1
  },
  {
    "source": "blog-post-generator",
    "target": "topic-idea-generator",
    "weight": 1
  },
  {
    "source": "blog-post-generator",
    "target": "swfl-context",
    "weight": 1
  },
  {
    "source": "brand-extractor",
    "target": "intake-parser",
    "weight": 1
  },
  {
    "source": "broken-link-finder",
    "target": "nightly-polish",
    "weight": 2
  },
  {
    "source": "broken-link-finder",
    "target": "launch-day-cutover",
    "weight": 1
  },
  {
    "source": "calendar-context-pull",
    "target": "daily-kickoff",
    "weight": 2
  },
  {
    "source": "calendar-context-pull",
    "target": "priority-ranker",
    "weight": 2
  },
  {
    "source": "case-study-from-customer",
    "target": "upgrade-nudge-detector",
    "weight": 1
  },
  {
    "source": "case-study-writer",
    "target": "day14-voice",
    "weight": 3
  },
  {
    "source": "chargeback-disputer",
    "target": "feedback-classifier",
    "weight": 1
  },
  {
    "source": "chatbot-prompt-builder",
    "target": "customer-build-day-1-bootstrap",
    "weight": 1
  },
  {
    "source": "chemistry-reading-parser",
    "target": "customer-visit-note-writer",
    "weight": 1
  },
  {
    "source": "churn-risk-scorer",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "cohort-retention-tracker",
    "target": "customer-ltv-calculator",
    "weight": 1
  },
  {
    "source": "cohort-retention-tracker",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "complaint-escalation",
    "target": "eod-update-writer",
    "weight": 2
  },
  {
    "source": "complaint-escalation",
    "target": "postmortem-writer",
    "weight": 2
  },
  {
    "source": "complaint-escalation",
    "target": "inbound-classifier",
    "weight": 1
  },
  {
    "source": "complaint-escalation",
    "target": "review-response",
    "weight": 1
  },
  {
    "source": "confidence-and-gate-statement",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "confidence-and-gate-statement",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "content-calendar-orchestrator",
    "target": "weekly-priorities-flush",
    "weight": 2
  },
  {
    "source": "content-calendar-orchestrator",
    "target": "hurricane-watch-poller",
    "weight": 1
  },
  {
    "source": "copy-writer",
    "target": "day14-voice",
    "weight": 3
  },
  {
    "source": "copy-writer",
    "target": "eod-update-writer",
    "weight": 2
  },
  {
    "source": "council-advisor-tuner",
    "target": "weekly-council-review",
    "weight": 3
  },
  {
    "source": "council-decision",
    "target": "day14-voice",
    "weight": 2
  },
  {
    "source": "council-decision-followup-tracker",
    "target": "approval-card-builder",
    "weight": 2
  },
  {
    "source": "council-decision-followup-tracker",
    "target": "weekly-council-review",
    "weight": 2
  },
  {
    "source": "council-decision-followup-tracker",
    "target": "council-question-quality-check",
    "weight": 1
  },
  {
    "source": "council-question-quality-check",
    "target": "action-bias-coach",
    "weight": 2
  },
  {
    "source": "council-question-quality-check",
    "target": "council-decision",
    "weight": 1
  },
  {
    "source": "customer-build-day-1-bootstrap",
    "target": "customer-readiness-check",
    "weight": 5
  },
  {
    "source": "customer-build-day-1-bootstrap",
    "target": "idempotent-bash-script",
    "weight": 3
  },
  {
    "source": "customer-build-day-1-bootstrap",
    "target": "template-forker",
    "weight": 3
  },
  {
    "source": "customer-build-day-1-bootstrap",
    "target": "eod-update-writer",
    "weight": 3
  },
  {
    "source": "customer-build-day-1-bootstrap",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "customer-build-day-1-bootstrap",
    "target": "approval-card-builder",
    "weight": 1
  },
  {
    "source": "customer-data-deletion-handler",
    "target": "inbound-classifier",
    "weight": 2
  },
  {
    "source": "customer-history-lookup",
    "target": "inbound-classifier",
    "weight": 1
  },
  {
    "source": "customer-history-lookup",
    "target": "lead-first-touch-personalizer",
    "weight": 1
  },
  {
    "source": "customer-history-lookup",
    "target": "complaint-escalation",
    "weight": 1
  },
  {
    "source": "customer-ltv-calculator",
    "target": "cohort-retention-tracker",
    "weight": 1
  },
  {
    "source": "customer-ltv-calculator",
    "target": "churn-risk-scorer",
    "weight": 1
  },
  {
    "source": "customer-readiness-check",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "customer-visit-note-writer",
    "target": "day14-voice",
    "weight": 2
  },
  {
    "source": "customer-voice-mapper",
    "target": "brand-extractor",
    "weight": 2
  },
  {
    "source": "daily-kickoff-telegram-formatter",
    "target": "daily-kickoff",
    "weight": 2
  },
  {
    "source": "data-retention-pruner",
    "target": "gdpr-data-export",
    "weight": 1
  },
  {
    "source": "decision-fatigue-detector",
    "target": "telegram-bridge",
    "weight": 1
  },
  {
    "source": "decision-fatigue-detector",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "decision-fatigue-detector",
    "target": "daily-eod",
    "weight": 1
  },
  {
    "source": "defer-vs-do-decider",
    "target": "inbound-classifier",
    "weight": 1
  },
  {
    "source": "defer-vs-do-decider",
    "target": "daily-eod",
    "weight": 1
  },
  {
    "source": "defer-vs-do-decider",
    "target": "weekly-priorities-flush",
    "weight": 1
  },
  {
    "source": "deploy-smoke-tester",
    "target": "launch-day-cutover",
    "weight": 1
  },
  {
    "source": "discount-floor-enforcer",
    "target": "eod-update-writer",
    "weight": 2
  },
  {
    "source": "discount-floor-enforcer",
    "target": "pricing-decision-helper",
    "weight": 1
  },
  {
    "source": "dispatch-day-of-reshuffler",
    "target": "dispatch-route-optimizer",
    "weight": 1
  },
  {
    "source": "dm-follow-up-detector",
    "target": "outreach-trigger",
    "weight": 2
  },
  {
    "source": "dm-follow-up-detector",
    "target": "warm-dm-personalizer",
    "weight": 1
  },
  {
    "source": "dm-follow-up-detector",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "dm-reply-classifier",
    "target": "lead-source-tracker",
    "weight": 1
  },
  {
    "source": "dns-drift-watcher",
    "target": "launch-day-cutover",
    "weight": 1
  },
  {
    "source": "dns-drift-watcher",
    "target": "uptime-monitor",
    "weight": 1
  },
  {
    "source": "dns-records-writer",
    "target": "launch-day-cutover",
    "weight": 1
  },
  {
    "source": "dossier-folder-initializer",
    "target": "intake-parser",
    "weight": 1
  },
  {
    "source": "dossier-folder-initializer",
    "target": "kickoff-call-scheduler",
    "weight": 1
  },
  {
    "source": "draft-promoter",
    "target": "skill-naming-validator",
    "weight": 1
  },
  {
    "source": "draft-promoter",
    "target": "skill-promotion-criteria",
    "weight": 1
  },
  {
    "source": "draft-promoter",
    "target": "pre-flight-verification-pass",
    "weight": 1
  },
  {
    "source": "draft-promoter",
    "target": "skill-registrar",
    "weight": 1
  },
  {
    "source": "draft-promoter",
    "target": "telegram-command-router",
    "weight": 1
  },
  {
    "source": "draft-promoter",
    "target": "risk-scoring",
    "weight": 1
  },
  {
    "source": "draft-promoter",
    "target": "skill-coverage-auditor",
    "weight": 1
  },
  {
    "source": "dunning-email-sequencer",
    "target": "subscription-pause-handler",
    "weight": 4
  },
  {
    "source": "dunning-email-sequencer",
    "target": "win-back-campaign-trigger",
    "weight": 1
  },
  {
    "source": "dunning-email-sequencer",
    "target": "inbound-classifier",
    "weight": 1
  },
  {
    "source": "email-fallback-channel",
    "target": "autonomous-health-check",
    "weight": 1
  },
  {
    "source": "email-newsletter-composer",
    "target": "content-calendar-orchestrator",
    "weight": 1
  },
  {
    "source": "emergent-skill-graduator",
    "target": "pattern-recurrence-detector",
    "weight": 1
  },
  {
    "source": "emergent-skill-graduator",
    "target": "skill-tree-grower",
    "weight": 2
  },
  {
    "source": "emergent-skill-graduator",
    "target": "council-decision",
    "weight": 2
  },
  {
    "source": "emergent-skill-graduator",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "emergent-skill-graduator",
    "target": "skill-registrar",
    "weight": 1
  },
  {
    "source": "energy-state-tracker",
    "target": "decision-fatigue-detector",
    "weight": 1
  },
  {
    "source": "eod-telegram-formatter",
    "target": "daily-eod",
    "weight": 3
  },
  {
    "source": "eod-update-writer",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "escalation-pattern-detector",
    "target": "confidence-and-gate-statement",
    "weight": 2
  },
  {
    "source": "escalation-pattern-detector",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "evacuation-zone-mapper",
    "target": "storm-week-comms",
    "weight": 1
  },
  {
    "source": "evacuation-zone-mapper",
    "target": "customer-readiness-check",
    "weight": 1
  },
  {
    "source": "event-rollup-summarizer",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "event-rollup-summarizer",
    "target": "eod-update-writer",
    "weight": 3
  },
  {
    "source": "event-rollup-summarizer",
    "target": "daily-eod",
    "weight": 1
  },
  {
    "source": "event-to-telegram-mapper",
    "target": "inbound-classifier",
    "weight": 2
  },
  {
    "source": "event-to-telegram-mapper",
    "target": "telegram-status-pusher",
    "weight": 3
  },
  {
    "source": "failed-payment-retry",
    "target": "dunning-email-sequencer",
    "weight": 2
  },
  {
    "source": "feedback-classifier",
    "target": "inbound-classifier",
    "weight": 2
  },
  {
    "source": "feedback-classifier",
    "target": "review-sentiment-scorer",
    "weight": 3
  },
  {
    "source": "feedback-classifier",
    "target": "vercel-route-resend-inbound",
    "weight": 1
  },
  {
    "source": "feedback-classifier",
    "target": "review-monitoring-poller",
    "weight": 1
  },
  {
    "source": "focus-block-protector",
    "target": "leaked-secret-cleanup",
    "weight": 1
  },
  {
    "source": "focus-block-protector",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "focus-block-protector",
    "target": "weekly-priorities-flush",
    "weight": 1
  },
  {
    "source": "followup-action-creator",
    "target": "daily-kickoff",
    "weight": 2
  },
  {
    "source": "followup-action-creator",
    "target": "customer-visit-note-writer",
    "weight": 1
  },
  {
    "source": "gap-moment-logger",
    "target": "skill-fire-wrapper",
    "weight": 1
  },
  {
    "source": "gdpr-data-export",
    "target": "inbound-classifier",
    "weight": 2
  },
  {
    "source": "git-fork-utility",
    "target": "template-forker",
    "weight": 1
  },
  {
    "source": "growth-always-on",
    "target": "skill-promotion-criteria",
    "weight": 1
  },
  {
    "source": "growth-always-on",
    "target": "skill-registrar",
    "weight": 1
  },
  {
    "source": "growth-cluster-gap-detector",
    "target": "skill-gap-detector",
    "weight": 1
  },
  {
    "source": "growth-cluster-gap-detector",
    "target": "growth-metrics-dashboard",
    "weight": 1
  },
  {
    "source": "growth-cluster-gap-detector",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "growth-metrics-dashboard",
    "target": "view-link-handoff",
    "weight": 2
  },
  {
    "source": "growth-metrics-dashboard",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "growth-skill-spec-generator",
    "target": "skill-spec-generator",
    "weight": 1
  },
  {
    "source": "growth-skill-spec-generator",
    "target": "growth-always-on",
    "weight": 1
  },
  {
    "source": "growth-skill-spec-generator",
    "target": "meta-growth-watcher",
    "weight": 1
  },
  {
    "source": "hurricane-watch-poller",
    "target": "storm-week-comms",
    "weight": 3
  },
  {
    "source": "incremental-scope-commit",
    "target": "pre-flight-verification-pass",
    "weight": 1
  },
  {
    "source": "incremental-scope-commit",
    "target": "agent-self-debug",
    "weight": 1
  },
  {
    "source": "intake-parser",
    "target": "approval-card-builder",
    "weight": 2
  },
  {
    "source": "internal-link-suggester",
    "target": "blog-draft-writer",
    "weight": 1
  },
  {
    "source": "internal-link-suggester",
    "target": "topic-idea-generator",
    "weight": 1
  },
  {
    "source": "jack-asleep-detector",
    "target": "calendar-context-pull",
    "weight": 2
  },
  {
    "source": "jack-asleep-detector",
    "target": "telegram-outbound-formatter",
    "weight": 1
  },
  {
    "source": "jack-asleep-detector",
    "target": "batching-quiet-hours",
    "weight": 2
  },
  {
    "source": "jack-language-decoder",
    "target": "telegram-inbound-parser",
    "weight": 2
  },
  {
    "source": "jack-language-decoder",
    "target": "telegram-command-router",
    "weight": 1
  },
  {
    "source": "kickoff-call-scheduler",
    "target": "day14-voice",
    "weight": 2
  },
  {
    "source": "kickoff-call-scheduler",
    "target": "approval-card-builder",
    "weight": 2
  },
  {
    "source": "launch-day-customer-email",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "launch-day-customer-email",
    "target": "launch-day-cutover",
    "weight": 1
  },
  {
    "source": "launch-day-customer-email",
    "target": "eod-update-writer",
    "weight": 2
  },
  {
    "source": "launch-day-cutover",
    "target": "approval-card-builder",
    "weight": 1
  },
  {
    "source": "launch-day-cutover",
    "target": "eod-update-writer",
    "weight": 1
  },
  {
    "source": "lead-first-touch-personalizer",
    "target": "approval-card-builder",
    "weight": 2
  },
  {
    "source": "lead-first-touch-personalizer",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "lead-source-tracker",
    "target": "outreach-trigger",
    "weight": 2
  },
  {
    "source": "lead-source-tracker",
    "target": "warm-dm-personalizer",
    "weight": 2
  },
  {
    "source": "lead-source-tracker",
    "target": "dossier-folder-initializer",
    "weight": 2
  },
  {
    "source": "lead-source-tracker",
    "target": "weekly-council-review",
    "weight": 2
  },
  {
    "source": "lead-source-tracker",
    "target": "kickoff-call-scheduler",
    "weight": 1
  },
  {
    "source": "lighthouse-runner",
    "target": "nightly-polish",
    "weight": 2
  },
  {
    "source": "lighthouse-runner",
    "target": "launch-day-cutover",
    "weight": 1
  },
  {
    "source": "linkedin-thought-leadership-post",
    "target": "content-calendar-orchestrator",
    "weight": 1
  },
  {
    "source": "local-event-detector",
    "target": "hurricane-watch-poller",
    "weight": 2
  },
  {
    "source": "local-event-detector",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "log-anomaly-detector",
    "target": "agent-self-debug",
    "weight": 1
  },
  {
    "source": "log-anomaly-detector",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "meta-growth-watcher",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "morning-briefing-generator",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "mrr-calculator",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "mrr-calculator",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "multi-command-parser",
    "target": "voice-message-transcriber",
    "weight": 2
  },
  {
    "source": "multi-command-parser",
    "target": "telegram-inbound-parser",
    "weight": 2
  },
  {
    "source": "nightly-polish-alert",
    "target": "nightly-polish",
    "weight": 3
  },
  {
    "source": "no-string-prefix-encoding",
    "target": "template-vs-product-decision",
    "weight": 1
  },
  {
    "source": "numbered-decision-rationale",
    "target": "action-bias-coach",
    "weight": 1
  },
  {
    "source": "numbered-decision-rationale",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "outreach-trigger",
    "target": "pricing-decision-helper",
    "weight": 1
  },
  {
    "source": "parallel-task-fanout-author",
    "target": "agent-self-time-budget",
    "weight": 2
  },
  {
    "source": "parallel-task-fanout-author",
    "target": "scheduled-task-prompt-author",
    "weight": 1
  },
  {
    "source": "pattern-recurrence-detector",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "payment-receipt-customizer",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "payment-receipt-customizer",
    "target": "browser-driven-vendor-setup",
    "weight": 2
  },
  {
    "source": "performance-regression-detector",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "phase-numbered-cross-reference",
    "target": "telegram-status-pusher",
    "weight": 1
  },
  {
    "source": "phase-numbered-cross-reference",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "phase-numbered-cross-reference",
    "target": "confidence-and-gate-statement",
    "weight": 1
  },
  {
    "source": "photo-watermarker",
    "target": "visit-photo-attacher",
    "weight": 2
  },
  {
    "source": "pipeline-end-to-end-test",
    "target": "customer-readiness-check",
    "weight": 1
  },
  {
    "source": "pipeline-end-to-end-test",
    "target": "customer-build-day-1-bootstrap",
    "weight": 1
  },
  {
    "source": "pipeline-end-to-end-test",
    "target": "launch-day-cutover",
    "weight": 1
  },
  {
    "source": "pipeline-end-to-end-test",
    "target": "launch-day-customer-email",
    "weight": 1
  },
  {
    "source": "pipeline-stuckness-detector",
    "target": "daily-kickoff",
    "weight": 2
  },
  {
    "source": "pipeline-stuckness-detector",
    "target": "intake-nudge-writer",
    "weight": 2
  },
  {
    "source": "pipeline-stuckness-detector",
    "target": "warm-dm-personalizer",
    "weight": 2
  },
  {
    "source": "pipeline-stuckness-detector",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "post-storm-damage-assessor",
    "target": "hurricane-watch-poller",
    "weight": 2
  },
  {
    "source": "post-storm-damage-assessor",
    "target": "day14-voice",
    "weight": 2
  },
  {
    "source": "post-storm-damage-assessor",
    "target": "warmth-calibrator",
    "weight": 1
  },
  {
    "source": "post-storm-damage-assessor",
    "target": "complaint-escalation",
    "weight": 1
  },
  {
    "source": "postmortem-writer",
    "target": "leaked-secret-cleanup",
    "weight": 2
  },
  {
    "source": "postmortem-writer",
    "target": "day14-voice",
    "weight": 2
  },
  {
    "source": "postmortem-writer",
    "target": "idempotent-bash-script",
    "weight": 1
  },
  {
    "source": "postmortem-writer",
    "target": "browser-driven-vendor-setup",
    "weight": 1
  },
  {
    "source": "postmortem-writer",
    "target": "session-recovery",
    "weight": 1
  },
  {
    "source": "power-outage-detector",
    "target": "storm-week-comms",
    "weight": 1
  },
  {
    "source": "pre-flight-verification-pass",
    "target": "daily-eod",
    "weight": 1
  },
  {
    "source": "prevention-skill-suggester",
    "target": "browser-driven-vendor-setup",
    "weight": 1
  },
  {
    "source": "prevention-skill-suggester",
    "target": "postmortem-writer",
    "weight": 1
  },
  {
    "source": "prevention-skill-suggester",
    "target": "pattern-recurrence-detector",
    "weight": 1
  },
  {
    "source": "pricing-decision-helper",
    "target": "council-decision",
    "weight": 8
  },
  {
    "source": "pricing-decision-helper",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "priority-ranker",
    "target": "daily-kickoff",
    "weight": 2
  },
  {
    "source": "priority-ranker",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "privacy-policy-keeper",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "read-aloud-checker",
    "target": "voice-drift-detector",
    "weight": 1
  },
  {
    "source": "recursive-growth-throttle",
    "target": "meta-growth-watcher",
    "weight": 4
  },
  {
    "source": "recursive-growth-throttle",
    "target": "growth-always-on",
    "weight": 1
  },
  {
    "source": "recursive-growth-throttle",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "refund-handler",
    "target": "mrr-calculator",
    "weight": 1
  },
  {
    "source": "refund-handler",
    "target": "feedback-classifier",
    "weight": 1
  },
  {
    "source": "refund-handler",
    "target": "inbound-classifier",
    "weight": 2
  },
  {
    "source": "refund-handler",
    "target": "chargeback-disputer",
    "weight": 2
  },
  {
    "source": "refund-handler",
    "target": "customer-history-lookup",
    "weight": 1
  },
  {
    "source": "repo-rename-after-fork",
    "target": "customer-readiness-check",
    "weight": 2
  },
  {
    "source": "repo-rename-after-fork",
    "target": "template-forker",
    "weight": 1
  },
  {
    "source": "returns-handler",
    "target": "shipping-label-generator",
    "weight": 1
  },
  {
    "source": "review-followup-tracker",
    "target": "review-response",
    "weight": 3
  },
  {
    "source": "review-followup-tracker",
    "target": "review-sentiment-scorer",
    "weight": 1
  },
  {
    "source": "review-followup-tracker",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "review-monitoring-poller",
    "target": "review-sentiment-scorer",
    "weight": 2
  },
  {
    "source": "review-monitoring-poller",
    "target": "review-response",
    "weight": 2
  },
  {
    "source": "review-request-sender",
    "target": "complaint-escalation",
    "weight": 1
  },
  {
    "source": "review-sentiment-scorer",
    "target": "review-response",
    "weight": 2
  },
  {
    "source": "review-sentiment-scorer",
    "target": "review-monitoring-poller",
    "weight": 1
  },
  {
    "source": "risk-scoring",
    "target": "approval-card-builder",
    "weight": 1
  },
  {
    "source": "risk-scoring",
    "target": "auto-approve-low-risk",
    "weight": 1
  },
  {
    "source": "risk-scoring",
    "target": "urgency-classifier",
    "weight": 1
  },
  {
    "source": "root-cause-categorizer",
    "target": "pattern-recurrence-detector",
    "weight": 2
  },
  {
    "source": "root-cause-categorizer",
    "target": "postmortem-writer",
    "weight": 2
  },
  {
    "source": "scheduled-task-portability-audit",
    "target": "pattern-recurrence-detector",
    "weight": 1
  },
  {
    "source": "scheduled-task-prompt-author",
    "target": "session-path-hardcode-detector",
    "weight": 1
  },
  {
    "source": "seo-keyword-cluster-builder",
    "target": "seo-keyword-fetcher",
    "weight": 1
  },
  {
    "source": "seo-keyword-cluster-builder",
    "target": "blog-post-generator",
    "weight": 1
  },
  {
    "source": "seo-keyword-cluster-builder",
    "target": "content-calendar-orchestrator",
    "weight": 1
  },
  {
    "source": "seo-keyword-cluster-builder",
    "target": "seo-city-page-builder",
    "weight": 1
  },
  {
    "source": "seo-keyword-fetcher",
    "target": "blog-draft-writer",
    "weight": 1
  },
  {
    "source": "seo-keyword-fetcher",
    "target": "topic-idea-generator",
    "weight": 1
  },
  {
    "source": "session-path-hardcode-detector",
    "target": "scheduled-task-prompt-author",
    "weight": 2
  },
  {
    "source": "shipping-label-generator",
    "target": "order-fulfillment-orchestrator",
    "weight": 1
  },
  {
    "source": "shortcuts-bridge",
    "target": "apple-watch-complication",
    "weight": 1
  },
  {
    "source": "skill-coverage-auditor",
    "target": "emergent-skill-graduator",
    "weight": 1
  },
  {
    "source": "skill-coverage-auditor",
    "target": "weekly-council-review",
    "weight": 2
  },
  {
    "source": "skill-deprecation-flagger",
    "target": "skill-invocation-monitor",
    "weight": 1
  },
  {
    "source": "skill-fire-wrapper",
    "target": "skill-coverage-auditor",
    "weight": 1
  },
  {
    "source": "skill-fire-wrapper",
    "target": "postmortem-writer",
    "weight": 1
  },
  {
    "source": "skill-gap-detector",
    "target": "skill-tree-grower",
    "weight": 1
  },
  {
    "source": "skill-gap-detector",
    "target": "pattern-recurrence-detector",
    "weight": 1
  },
  {
    "source": "skill-gap-detector",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "skill-invocation-monitor",
    "target": "storm-week-comms",
    "weight": 1
  },
  {
    "source": "skill-invocation-monitor",
    "target": "chemistry-reading-parser",
    "weight": 1
  },
  {
    "source": "skill-invocation-monitor",
    "target": "evacuation-zone-mapper",
    "weight": 1
  },
  {
    "source": "skill-invocation-monitor",
    "target": "complaint-escalation",
    "weight": 1
  },
  {
    "source": "skill-merge-suggester",
    "target": "skill-coverage-auditor",
    "weight": 1
  },
  {
    "source": "skill-naming-validator",
    "target": "skill-registrar",
    "weight": 1
  },
  {
    "source": "skill-naming-validator",
    "target": "skill-tree-grower",
    "weight": 1
  },
  {
    "source": "skill-naming-validator",
    "target": "skill-spec-generator",
    "weight": 1
  },
  {
    "source": "skill-promotion-criteria",
    "target": "photo-watermarker",
    "weight": 1
  },
  {
    "source": "skill-promotion-criteria",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "skill-promotion-criteria",
    "target": "skill-tree-grower",
    "weight": 2
  },
  {
    "source": "skill-promotion-criteria",
    "target": "emergent-skill-graduator",
    "weight": 1
  },
  {
    "source": "skill-registrar",
    "target": "skill-spec-generator",
    "weight": 2
  },
  {
    "source": "skill-registrar",
    "target": "skill-naming-validator",
    "weight": 1
  },
  {
    "source": "skill-registrar",
    "target": "skill-tree-grower",
    "weight": 2
  },
  {
    "source": "skill-registrar",
    "target": "pre-flight-verification-pass",
    "weight": 1
  },
  {
    "source": "skill-spec-generator",
    "target": "skill-naming-validator",
    "weight": 2
  },
  {
    "source": "skill-spec-generator",
    "target": "skill-tree-grower",
    "weight": 2
  },
  {
    "source": "skill-tree-grower",
    "target": "skill-gap-detector",
    "weight": 2
  },
  {
    "source": "skill-tree-grower",
    "target": "skill-coverage-auditor",
    "weight": 1
  },
  {
    "source": "skill-tree-grower",
    "target": "skill-promotion-criteria",
    "weight": 2
  },
  {
    "source": "skill-tree-grower",
    "target": "skill-naming-validator",
    "weight": 1
  },
  {
    "source": "skill-tree-grower",
    "target": "emergent-skill-graduator",
    "weight": 2
  },
  {
    "source": "skill-tree-grower",
    "target": "pattern-recurrence-detector",
    "weight": 1
  },
  {
    "source": "skill-tree-grower",
    "target": "skill-spec-generator",
    "weight": 1
  },
  {
    "source": "skill-tree-grower",
    "target": "skill-registrar",
    "weight": 1
  },
  {
    "source": "skill-version-bumper",
    "target": "draft-promoter",
    "weight": 1
  },
  {
    "source": "skill-version-bumper",
    "target": "skill-merge-suggester",
    "weight": 1
  },
  {
    "source": "social-cross-post",
    "target": "blog-post-generator",
    "weight": 1
  },
  {
    "source": "social-cross-post",
    "target": "content-calendar-orchestrator",
    "weight": 1
  },
  {
    "source": "ssl-expiry-watcher",
    "target": "approval-card-builder",
    "weight": 2
  },
  {
    "source": "ssl-expiry-watcher",
    "target": "nightly-polish",
    "weight": 1
  },
  {
    "source": "ssl-provisioning-verifier",
    "target": "launch-day-cutover",
    "weight": 1
  },
  {
    "source": "ssl-provisioning-verifier",
    "target": "nightly-polish",
    "weight": 2
  },
  {
    "source": "storm-week-comms",
    "target": "eod-update-writer",
    "weight": 2
  },
  {
    "source": "stripe-payment-link-creator",
    "target": "eod-update-writer",
    "weight": 1
  },
  {
    "source": "stripe-test-mode-validator",
    "target": "stripe-webhook-verifier",
    "weight": 1
  },
  {
    "source": "stripe-test-mode-validator",
    "target": "dossier-folder-initializer",
    "weight": 1
  },
  {
    "source": "stripe-webhook-verifier",
    "target": "dossier-folder-initializer",
    "weight": 1
  },
  {
    "source": "stripe-webhook-verifier",
    "target": "kickoff-call-scheduler",
    "weight": 1
  },
  {
    "source": "subscription-pause-handler",
    "target": "dunning-email-sequencer",
    "weight": 2
  },
  {
    "source": "subscription-pause-handler",
    "target": "inbound-classifier",
    "weight": 2
  },
  {
    "source": "subscription-pause-handler",
    "target": "refund-handler",
    "weight": 1
  },
  {
    "source": "subscription-pause-handler",
    "target": "failed-payment-retry",
    "weight": 1
  },
  {
    "source": "supabase-event-listener",
    "target": "dossier-folder-initializer",
    "weight": 1
  },
  {
    "source": "supabase-event-listener",
    "target": "kickoff-call-scheduler",
    "weight": 1
  },
  {
    "source": "supabase-event-listener",
    "target": "telegram-status-pusher",
    "weight": 8
  },
  {
    "source": "supabase-event-listener",
    "target": "intake-parser",
    "weight": 1
  },
  {
    "source": "supabase-event-listener",
    "target": "customer-readiness-check",
    "weight": 2
  },
  {
    "source": "supabase-event-listener",
    "target": "customer-build-day-1-bootstrap",
    "weight": 1
  },
  {
    "source": "supabase-event-listener",
    "target": "inbound-classifier",
    "weight": 1
  },
  {
    "source": "supabase-event-listener",
    "target": "telegram-approval-card",
    "weight": 1
  },
  {
    "source": "supabase-event-listener",
    "target": "launch-day-customer-email",
    "weight": 1
  },
  {
    "source": "supabase-event-listener",
    "target": "complaint-escalation",
    "weight": 1
  },
  {
    "source": "supabase-event-listener",
    "target": "leaked-secret-cleanup",
    "weight": 1
  },
  {
    "source": "swfl-vertical-deep-dives",
    "target": "copy-writer",
    "weight": 1
  },
  {
    "source": "swfl-vertical-deep-dives",
    "target": "inbound-classifier",
    "weight": 1
  },
  {
    "source": "swfl-vertical-deep-dives",
    "target": "customer-visit-note-writer",
    "weight": 1
  },
  {
    "source": "swfl-vertical-deep-dives",
    "target": "review-response",
    "weight": 1
  },
  {
    "source": "telegram-approval-card",
    "target": "approval-card-builder",
    "weight": 3
  },
  {
    "source": "telegram-approval-card",
    "target": "batching-quiet-hours",
    "weight": 2
  },
  {
    "source": "telegram-approval-card",
    "target": "short-link-router",
    "weight": 2
  },
  {
    "source": "telegram-approval-card",
    "target": "telegram-status-pusher",
    "weight": 1
  },
  {
    "source": "telegram-bridge",
    "target": "voice-drift-detector",
    "weight": 1
  },
  {
    "source": "telegram-bridge",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "telegram-bridge",
    "target": "telegram-command-router",
    "weight": 3
  },
  {
    "source": "telegram-command-router",
    "target": "telegram-inbound-parser",
    "weight": 3
  },
  {
    "source": "telegram-command-router",
    "target": "mrr-calculator",
    "weight": 1
  },
  {
    "source": "telegram-command-router",
    "target": "customer-history-lookup",
    "weight": 2
  },
  {
    "source": "telegram-command-router",
    "target": "council-decision",
    "weight": 2
  },
  {
    "source": "telegram-command-router",
    "target": "voice-message-transcriber",
    "weight": 1
  },
  {
    "source": "telegram-command-router",
    "target": "approval-card-builder",
    "weight": 1
  },
  {
    "source": "telegram-conversation-state",
    "target": "telegram-inbound-parser",
    "weight": 2
  },
  {
    "source": "telegram-conversation-state",
    "target": "telegram-outbound-formatter",
    "weight": 1
  },
  {
    "source": "telegram-conversation-state",
    "target": "telegram-command-router",
    "weight": 1
  },
  {
    "source": "telegram-inbound-parser",
    "target": "telegram-conversation-state",
    "weight": 2
  },
  {
    "source": "telegram-inbound-parser",
    "target": "voice-message-transcriber",
    "weight": 1
  },
  {
    "source": "telegram-inbound-parser",
    "target": "telegram-command-router",
    "weight": 1
  },
  {
    "source": "telegram-outbound-formatter",
    "target": "voice-drift-detector",
    "weight": 1
  },
  {
    "source": "telegram-status-pusher",
    "target": "event-to-telegram-mapper",
    "weight": 3
  },
  {
    "source": "telegram-status-pusher",
    "target": "telegram-approval-card",
    "weight": 2
  },
  {
    "source": "telegram-status-pusher",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "telegram-status-pusher",
    "target": "urgency-classifier",
    "weight": 3
  },
  {
    "source": "telegram-status-pusher",
    "target": "jack-asleep-detector",
    "weight": 3
  },
  {
    "source": "telegram-status-pusher",
    "target": "telegram-outbound-formatter",
    "weight": 3
  },
  {
    "source": "telegram-status-pusher",
    "target": "batching-quiet-hours",
    "weight": 2
  },
  {
    "source": "template-version-tracker",
    "target": "template-forker",
    "weight": 3
  },
  {
    "source": "template-version-tracker",
    "target": "upsell-detection",
    "weight": 2
  },
  {
    "source": "tomorrow-plan-extractor",
    "target": "eod-update-writer",
    "weight": 1
  },
  {
    "source": "tomorrow-plan-extractor",
    "target": "daily-eod",
    "weight": 1
  },
  {
    "source": "topic-idea-generator",
    "target": "swfl-context",
    "weight": 2
  },
  {
    "source": "topic-idea-generator",
    "target": "local-event-detector",
    "weight": 1
  },
  {
    "source": "topic-idea-generator",
    "target": "swfl-vertical-deep-dives",
    "weight": 2
  },
  {
    "source": "topic-idea-generator",
    "target": "blog-draft-writer",
    "weight": 1
  },
  {
    "source": "upgrade-nudge-detector",
    "target": "customer-history-lookup",
    "weight": 1
  },
  {
    "source": "upgrade-nudge-detector",
    "target": "failed-payment-retry",
    "weight": 1
  },
  {
    "source": "upsell-detection",
    "target": "walk-away-detector",
    "weight": 2
  },
  {
    "source": "upsell-detection",
    "target": "day14-voice",
    "weight": 2
  },
  {
    "source": "upsell-detection",
    "target": "discount-floor-enforcer",
    "weight": 3
  },
  {
    "source": "upsell-detection",
    "target": "customer-history-lookup",
    "weight": 2
  },
  {
    "source": "upsell-detection",
    "target": "pricing-decision-helper",
    "weight": 2
  },
  {
    "source": "upsell-detection",
    "target": "approval-card-builder",
    "weight": 2
  },
  {
    "source": "upsell-detection",
    "target": "inbound-classifier",
    "weight": 2
  },
  {
    "source": "upsell-detection",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "uptime-monitor",
    "target": "dns-drift-watcher",
    "weight": 1
  },
  {
    "source": "uptime-monitor",
    "target": "daily-kickoff",
    "weight": 1
  },
  {
    "source": "uptime-monitor",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "urgency-classifier",
    "target": "telegram-outbound-formatter",
    "weight": 1
  },
  {
    "source": "urgency-classifier",
    "target": "batching-quiet-hours",
    "weight": 1
  },
  {
    "source": "urgency-classifier",
    "target": "jack-asleep-detector",
    "weight": 1
  },
  {
    "source": "urgency-classifier",
    "target": "telegram-status-pusher",
    "weight": 1
  },
  {
    "source": "vercel-deployer",
    "target": "template-forker",
    "weight": 2
  },
  {
    "source": "vercel-deployer",
    "target": "launch-day-cutover",
    "weight": 1
  },
  {
    "source": "vercel-route-cal-com-webhook",
    "target": "intake-nudge-writer",
    "weight": 2
  },
  {
    "source": "vercel-route-cal-com-webhook",
    "target": "customer-readiness-check",
    "weight": 3
  },
  {
    "source": "vercel-route-cal-com-webhook",
    "target": "customer-build-day-1-bootstrap",
    "weight": 1
  },
  {
    "source": "vercel-route-intake-webhook",
    "target": "kickoff-call-scheduler",
    "weight": 2
  },
  {
    "source": "vercel-route-intake-webhook",
    "target": "intake-parser",
    "weight": 2
  },
  {
    "source": "vercel-route-intake-webhook",
    "target": "dossier-folder-initializer",
    "weight": 1
  },
  {
    "source": "vercel-route-resend-inbound",
    "target": "inbound-classifier",
    "weight": 3
  },
  {
    "source": "vercel-route-stripe-webhook",
    "target": "dossier-folder-initializer",
    "weight": 2
  },
  {
    "source": "vercel-route-stripe-webhook",
    "target": "telegram-status-pusher",
    "weight": 1
  },
  {
    "source": "vercel-route-stripe-webhook",
    "target": "stripe-webhook-verifier",
    "weight": 1
  },
  {
    "source": "view-link-handoff",
    "target": "morning-headline-format",
    "weight": 1
  },
  {
    "source": "view-link-handoff",
    "target": "daily-eod",
    "weight": 1
  },
  {
    "source": "voice-drift-detector",
    "target": "eod-update-writer",
    "weight": 1
  },
  {
    "source": "voice-drift-detector",
    "target": "blog-draft-writer",
    "weight": 1
  },
  {
    "source": "voice-drift-detector",
    "target": "outreach-trigger",
    "weight": 1
  },
  {
    "source": "voice-drift-detector",
    "target": "warm-dm-personalizer",
    "weight": 1
  },
  {
    "source": "voice-drift-detector",
    "target": "review-response",
    "weight": 1
  },
  {
    "source": "voice-message-transcriber",
    "target": "telegram-inbound-parser",
    "weight": 2
  },
  {
    "source": "voice-message-transcriber",
    "target": "multi-command-parser",
    "weight": 3
  },
  {
    "source": "voice-message-transcriber",
    "target": "telegram-command-router",
    "weight": 1
  },
  {
    "source": "voice-tts-out",
    "target": "day14-voice",
    "weight": 2
  },
  {
    "source": "voice-tts-out",
    "target": "telegram-outbound-formatter",
    "weight": 1
  },
  {
    "source": "walk-away-detector",
    "target": "discount-floor-enforcer",
    "weight": 1
  },
  {
    "source": "walk-away-detector",
    "target": "day14-voice",
    "weight": 1
  },
  {
    "source": "warm-dm-personalizer",
    "target": "day14-voice",
    "weight": 2
  },
  {
    "source": "warm-dm-personalizer",
    "target": "outreach-trigger",
    "weight": 2
  },
  {
    "source": "warmth-calibrator",
    "target": "launch-day-customer-email",
    "weight": 4
  },
  {
    "source": "warmth-calibrator",
    "target": "eod-update-writer",
    "weight": 2
  },
  {
    "source": "watchdog-self-restarter",
    "target": "autonomous-health-check",
    "weight": 1
  },
  {
    "source": "weekly-priorities-flush",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "win-back-campaign-trigger",
    "target": "warm-dm-personalizer",
    "weight": 1
  },
  {
    "source": "win-back-campaign-trigger",
    "target": "inbound-classifier",
    "weight": 2
  },
  {
    "source": "win-back-campaign-trigger",
    "target": "dunning-email-sequencer",
    "weight": 1
  },
  {
    "source": "yesterday-wins-extractor",
    "target": "daily-kickoff",
    "weight": 2
  },
  {
    "source": "yesterday-wins-extractor",
    "target": "weekly-council-review",
    "weight": 1
  },
  {
    "source": "youtube-script-from-blog",
    "target": "content-calendar-orchestrator",
    "weight": 1
  },
  {
    "source": "zero-friction-handoff",
    "target": "morning-briefing-generator",
    "weight": 1
  }
];

export const NODE_COUNT = 270;
export const EDGE_COUNT = 431;

/** Top 20 most-connected skills */
export const HUBS: readonly { id: string; total: number; inDegree: number; outDegree: number }[] = [
  {
    "id": "weekly-council-review",
    "total": 28,
    "inDegree": 28,
    "outDegree": 0
  },
  {
    "id": "day14-voice",
    "total": 24,
    "inDegree": 24,
    "outDegree": 0
  },
  {
    "id": "daily-kickoff",
    "total": 18,
    "inDegree": 18,
    "outDegree": 0
  },
  {
    "id": "inbound-classifier",
    "total": 16,
    "inDegree": 16,
    "outDegree": 0
  },
  {
    "id": "approval-card-builder",
    "total": 14,
    "inDegree": 14,
    "outDegree": 0
  },
  {
    "id": "skill-tree-grower",
    "total": 14,
    "inDegree": 6,
    "outDegree": 8
  },
  {
    "id": "eod-update-writer",
    "total": 13,
    "inDegree": 12,
    "outDegree": 1
  },
  {
    "id": "telegram-status-pusher",
    "total": 13,
    "inDegree": 6,
    "outDegree": 7
  },
  {
    "id": "telegram-command-router",
    "total": 12,
    "inDegree": 6,
    "outDegree": 6
  },
  {
    "id": "customer-build-day-1-bootstrap",
    "total": 11,
    "inDegree": 5,
    "outDegree": 6
  },
  {
    "id": "launch-day-cutover",
    "total": 11,
    "inDegree": 9,
    "outDegree": 2
  },
  {
    "id": "supabase-event-listener",
    "total": 11,
    "inDegree": 0,
    "outDegree": 11
  },
  {
    "id": "postmortem-writer",
    "total": 10,
    "inDegree": 5,
    "outDegree": 5
  },
  {
    "id": "blog-post-generator",
    "total": 9,
    "inDegree": 2,
    "outDegree": 7
  },
  {
    "id": "complaint-escalation",
    "total": 9,
    "inDegree": 5,
    "outDegree": 4
  },
  {
    "id": "skill-registrar",
    "total": 9,
    "inDegree": 5,
    "outDegree": 4
  },
  {
    "id": "upsell-detection",
    "total": 9,
    "inDegree": 1,
    "outDegree": 8
  },
  {
    "id": "voice-drift-detector",
    "total": 9,
    "inDegree": 4,
    "outDegree": 5
  },
  {
    "id": "content-calendar-orchestrator",
    "total": 8,
    "inDegree": 6,
    "outDegree": 2
  },
  {
    "id": "daily-eod",
    "total": 8,
    "inDegree": 8,
    "outDegree": 0
  }
];

/** Skills with no inbound or outbound references (potential cleanup) */
export const ORPHANS: readonly string[] = [
  "abandoned-cart-recovery",
  "appointment-availability-publisher",
  "appointment-booking-engine",
  "appointment-no-show-recovery",
  "appointment-recurring-rebooker",
  "appointment-reminder-sequencer",
  "batch-post-scheduler",
  "comment-engagement-tracker",
  "cross-business-content-calendar",
  "cross-business-prioritizer",
  "customer-service-triage",
  "dispatch-eta-publisher",
  "dispatch-tech-tracker",
  "ecom-stripe-payment-link-setup",
  "error-recovery-resume",
  "etsy-listing-writer",
  "etsy-pricing-validator",
  "etsy-product-mockup-prompts",
  "etsy-shop-policies-generator",
  "etsy-tag-researcher",
  "image-generator",
  "instagram-reel-caption-writer",
  "inventory-tracker",
  "launch-agent-setup",
  "multi-tenant-mrr-aggregator",
  "next-app-router-conventions",
  "no-edge-in-memory-state",
  "no-hardcoded-tz-offset",
  "per-tenant-daily-rollup",
  "photo-proof-archive",
  "photo-proof-customer-portal",
  "photo-proof-uploader",
  "photo-proof-watermarker",
  "pod-design-brief-generator",
  "pod-niche-researcher",
  "pod-product-mix-recommender",
  "pricing-margin-calculator",
  "printify-product-creator",
  "proactive-monitor",
  "product-catalog-manager",
  "product-photo-organizer",
  "project-change-order-handler",
  "project-completion-walkthrough",
  "project-deposit-balance-billing",
  "project-gantt-renderer",
  "project-milestone-tracker",
  "project-photo-stream",
  "social-analytics-rollup",
  "tenant-context-switcher",
  "thumbnail-generator",
  "tiktok-caption-writer",
  "twitter-video-poster",
  "vertical-9-16-edit-pipeline",
  "video-clipper-ffmpeg",
  "viral-hook-rewriter",
  "whisper-transcription-captioner",
  "youtube-shorts-caption-writer"
];
