"use client";

/**
 * CinematicImage — wraps a generated Gemini image with the treatments that
 * make it feel native to the landing page instead of "stock photo pasted in":
 *
 *   - Fade-in + soft zoom on first scroll into view (Cursor/Linear pattern)
 *   - Optional gradient overlay (lets us tint or fade an edge to integrate
 *     with surrounding section background)
 *   - Optional mix-blend mode (ambient hero backdrop uses `screen` to bond
 *     with the mesh gradient underneath)
 *   - Parallax y-translate driven by section scroll (subtle, ~24px)
 *   - Honors reduced motion — static, no transforms
 *
 * The image src lives under /images/landing/<slug>.png and is generated by
 * scripts/_internal/landing-images-2026-06-02.mjs, which Jack runs from his
 * Mac terminal because the sandbox can't reach generativelanguage.googleapis.com.
 *
 * If the file doesn't exist yet, the browser shows the fallback frame (a
 * subtle gradient that matches the section) so the layout doesn't collapse.
 *
 * SSR-safe: server renders the <img> + overlay structure so first paint is
 * complete; client takes over for motion only.
 */

import { motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";
import type { CSSProperties, ReactNode } from "react";

interface CinematicImageProps {
  /** Path under /public, e.g. "/images/landing/hero-ambient.png". */
  src: string;
  /** Alt text — required for a11y. Decorative? Pass "". */
  alt: string;
  /**
   * Treatment preset:
   *   - "ambient"   : fills the parent absolutely, mix-blend-screen, low opacity
   *   - "card"      : fills parent absolutely, dark scrim at bottom for legible text
   *   - "tile"      : standalone illustration in normal flow, soft rounded frame
   *   - "scrim"     : full-bleed dark backdrop with vignette
   */
  treatment?: "ambient" | "card" | "tile" | "scrim";
  /** Custom overlay gradient — overrides the preset's gradient. */
  overlay?: string;
  /** Object-position override (default "center"). */
  position?: string;
  /** Force a specific aspect-ratio on the tile container. */
  aspect?: string;
  /** Optional className for the outer wrapper. */
  className?: string;
  /** Optional children rendered over the image — useful for captions. */
  children?: ReactNode;
  /** Disable parallax even when motion is allowed. */
  staticPosition?: boolean;
}

export function CinematicImage({
  src,
  alt,
  treatment = "tile",
  overlay,
  position = "center",
  aspect,
  className = "",
  children,
  staticPosition = false,
}: CinematicImageProps) {
  const reduce = useReducedMotion();
  const ref = useRef<HTMLDivElement | null>(null);

  // Subtle scroll-driven parallax. Each instance computes its own progress
  // relative to its viewport position, so a hero backdrop drifts up while a
  // case-card image floats down — adds depth without choreography work.
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start end", "end start"],
  });
  const y = useTransform(scrollYProgress, [0, 1], [12, -12]);
  const scale = useTransform(scrollYProgress, [0, 0.5, 1], [1.04, 1.0, 1.04]);

  const presets: Record<
    NonNullable<CinematicImageProps["treatment"]>,
    { wrap: CSSProperties; overlay: string; imgStyle: CSSProperties }
  > = {
    ambient: {
      wrap: {
        position: "absolute",
        inset: 0,
        overflow: "hidden",
        pointerEvents: "none",
        zIndex: 0,
      },
      overlay:
        "linear-gradient(180deg, rgba(248,246,241,0.20) 0%, rgba(248,246,241,0.55) 60%, rgba(248,246,241,0.95) 100%)",
      imgStyle: {
        width: "100%",
        height: "100%",
        objectFit: "cover",
        objectPosition: position,
        opacity: 0.55,
        mixBlendMode: "screen",
      },
    },
    card: {
      wrap: {
        position: "absolute",
        inset: 0,
        overflow: "hidden",
        pointerEvents: "none",
        zIndex: 0,
        borderRadius: "inherit",
      },
      overlay:
        "linear-gradient(180deg, rgba(255,255,255,0.05) 0%, rgba(15,23,42,0.05) 40%, rgba(15,23,42,0.55) 100%)",
      imgStyle: {
        width: "100%",
        height: "100%",
        objectFit: "cover",
        objectPosition: position,
        opacity: 0.85,
      },
    },
    tile: {
      wrap: {
        position: "relative",
        overflow: "hidden",
        borderRadius: 12,
        boxShadow: "0 24px 60px -28px rgba(15,23,42,0.30)",
        background:
          "radial-gradient(120% 80% at 50% 0%, rgba(239,108,51,0.06), rgba(239,108,51,0) 70%), #0a0e14",
      },
      overlay:
        "linear-gradient(180deg, rgba(10,14,20,0) 60%, rgba(10,14,20,0.45) 100%)",
      imgStyle: {
        display: "block",
        width: "100%",
        height: "100%",
        objectFit: "cover",
        objectPosition: position,
      },
    },
    scrim: {
      wrap: {
        position: "absolute",
        inset: 0,
        overflow: "hidden",
        pointerEvents: "none",
        zIndex: 0,
        borderRadius: "inherit",
      },
      overlay:
        "radial-gradient(140% 100% at 50% 50%, rgba(10,14,20,0) 0%, rgba(10,14,20,0.55) 70%, rgba(10,14,20,0.85) 100%)",
      imgStyle: {
        width: "100%",
        height: "100%",
        objectFit: "cover",
        objectPosition: position,
        opacity: 0.75,
      },
    },
  };

  const preset = presets[treatment];
  const overlayBg = overlay ?? preset.overlay;

  const wrapStyle: CSSProperties = {
    ...preset.wrap,
    ...(aspect ? { aspectRatio: aspect } : {}),
  };

  // framer-motion accepts MotionValue<number> for `y` and `scale` on a
  // motion element's style prop, but React's CSSProperties typings don't,
  // so we widen via unknown only on the animated branch.
  const motionStyle: CSSProperties =
    reduce || staticPosition
      ? { width: "100%", height: "100%" }
      : ({ width: "100%", height: "100%", y, scale } as unknown as CSSProperties);

  return (
    <div ref={ref} className={className} style={wrapStyle}>
      <motion.div
        initial={reduce ? undefined : { opacity: 0 }}
        whileInView={reduce ? undefined : { opacity: 1 }}
        viewport={{ once: true, amount: 0.2 }}
        transition={{ duration: 0.9, ease: [0.22, 1, 0.36, 1] }}
        style={motionStyle}
      >
        <img
          src={src}
          alt={alt}
          loading="lazy"
          decoding="async"
          style={preset.imgStyle}
          onError={(e) => {
            // If the file isn't generated yet, hide the broken-image icon and
            // let the wrapper's background gradient stand in.
            (e.currentTarget as HTMLImageElement).style.opacity = "0";
          }}
        />
      </motion.div>
      <div
        aria-hidden
        style={{
          position: "absolute",
          inset: 0,
          background: overlayBg,
          pointerEvents: "none",
        }}
      />
      {children && (
        <div style={{ position: "relative", zIndex: 1 }}>{children}</div>
      )}
    </div>
  );
}
