/**
 * End-to-end contract test: the Marque creative pipeline -> the Day14 backend.
 *
 * The pipeline that generates ad variants is a Python skill
 * (~/Claude/Projects/DAY14/Marque/scripts). The receiver is this repo's
 * /api/webhooks/marque route. Nothing type-checks across that boundary, so the
 * only thing keeping them in sync is a fixture of REAL signed payloads produced
 * by the Python side and replayed through the real TypeScript handler here.
 *
 * tests/fixtures/marque-pipeline-payloads.json was generated by
 * marque_matrix.py + marque_post.py under the same test secret this file uses.
 * If the Python changes its serialisation, its signing, or its field names,
 * these tests fail — which is the entire point.
 *
 * Regenerate with:
 *   python3 ~/Claude/Projects/DAY14/Marque/scripts/... (see marque-service-line memory)
 */

import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";

import payloads from "./fixtures/marque-pipeline-payloads.json";
import { parseVariantId } from "@/lib/marque-taxonomy";

const SECRET = "test-ingest-secret";
const SIGNATURE_HEADER = "x-day14-signature";

let TMP_HOME: string;

async function freshPost() {
  vi.resetModules();
  const mod = await import("../src/app/api/webhooks/marque/route");
  return mod.POST as (req: Request) => Promise<Response>;
}

function requestFrom(p: { body: string; signature: string }, sig?: string): Request {
  return new Request("http://localhost/api/webhooks/marque", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-day14-brand": "marque",
      [SIGNATURE_HEADER]: sig ?? p.signature,
    },
    body: p.body,
  });
}

beforeEach(async () => {
  TMP_HOME = await fs.mkdtemp(path.join(os.tmpdir(), "marque-e2e-"));
  process.env.HOME = TMP_HOME;
  process.env.DAY14_INGEST_SECRET = SECRET;
  // No live DB — the handler's graceful no-op-log path.
  delete process.env.NEXT_PUBLIC_SUPABASE_URL;
  delete process.env.SUPABASE_SERVICE_ROLE_KEY;
});

afterEach(async () => {
  delete process.env.DAY14_INGEST_SECRET;
  await fs.rm(TMP_HOME, { recursive: true, force: true }).catch(() => {});
});

describe("marque pipeline -> backend, end to end", () => {
  test("the fixture is a real batch, not a stub", () => {
    expect(payloads.length).toBeGreaterThanOrEqual(4);
    for (const p of payloads) {
      expect(typeof p.body).toBe("string");
      expect(p.signature).toMatch(/^[0-9a-f]{64}$/);
    }
  });

  test("Python's HMAC verifies under Node's crypto, byte for byte", () => {
    for (const p of payloads) {
      const expected = crypto
        .createHmac("sha256", SECRET)
        .update(Buffer.from(p.body, "utf-8"))
        .digest("hex");
      expect(expected, `signature mismatch for ${p.body.slice(0, 60)}`).toBe(p.signature);
    }
  });

  test("every generated variant is accepted by the live route handler", async () => {
    const POST = await freshPost();
    for (const p of payloads) {
      const res = await POST(requestFrom(p));
      expect(res.status, `rejected: ${p.body.slice(0, 80)}`).toBe(200);
    }
  });

  test("the variant id survives the round trip and still parses as a tag", () => {
    for (const p of payloads) {
      const rec = JSON.parse(p.body);
      expect(rec.kind).toBe("marque-ad-scored");
      expect(rec.brand).toBe("marque");
      expect(rec.source).toBe("marque-pipeline");

      const tag = parseVariantId(rec.external_id);
      expect(tag, `unparseable external_id: ${rec.external_id}`).not.toBeNull();
      // The id is not just an opaque key — it must agree with the payload it carries.
      expect(tag!.hook).toBe(rec.payload.hook);
      expect(tag!.angle).toBe(rec.payload.angle);
      expect(tag!.format).toBe(rec.payload.format);
      expect(tag!.ratio).toBe(rec.payload.ratio);
      expect(tag!.channel).toBe(rec.payload.channel);
      expect(tag!.product).toBe(rec.payload.product);
    }
  });

  test("the batch is a test, not a pile — distinct hooks and angles", () => {
    const recs = payloads.map((p) => JSON.parse(p.body));
    expect(new Set(recs.map((r) => r.payload.hook)).size).toBe(recs.length);
    expect(new Set(recs.map((r) => r.external_id)).size).toBe(recs.length);
  });

  test("every variant carries a concept — a category is not a brief", () => {
    for (const p of payloads) {
      const rec = JSON.parse(p.body);
      expect(rec.payload.concept.length).toBeGreaterThan(20);
    }
  });

  test("re-posting the same batch is idempotent, not a duplicate", async () => {
    const POST = await freshPost();
    const first = await POST(requestFrom(payloads[0]!));
    expect(first.status).toBe(200);
    const second = await POST(requestFrom(payloads[0]!));
    expect(second.status).toBe(200);
  });

  test("a tampered payload under a valid-looking signature is rejected", async () => {
    const POST = await freshPost();
    const p = payloads[0]!;
    const tampered = { ...p, body: p.body.replace("mug-warmer", "someone-elses-product") };
    const res = await POST(requestFrom(tampered, p.signature));
    expect(res.status).toBe(401);
  });

  test("a payload signed under the wrong secret is rejected", async () => {
    const POST = await freshPost();
    const p = payloads[0]!;
    const wrong = crypto.createHmac("sha256", "not-the-secret").update(p.body).digest("hex");
    const res = await POST(requestFrom(p, wrong));
    expect(res.status).toBe(401);
  });
});
