import Link from "next/link";
import { notFound } from "next/navigation";
import { loadTenantOps, type REEvaluation } from "@/lib/admin-state";
import type { REProperty } from "@/lib/realty-gameplan";
import { buildContract, contractTypeName, CONTRACT_LEGAL_NOTICE } from "@/lib/realty-contracts";
import { AdminNav, ADMIN_CSS } from "../../../../layout-bits";
import { PrintButton } from "./print-button";

export const dynamic = "force-dynamic";

const CONTRACT_CSS = `
.admin-shell .contract-toolbar { display:flex; gap:12px; align-items:center; flex-wrap:wrap; margin-bottom:18px; }
.admin-shell .contract-doc { background:#fff; border:1px solid var(--border); border-radius:var(--r-md); padding:40px 44px; max-width:800px; }
.admin-shell .contract-notice { background:var(--red-soft); border:1px solid #f3c9c5; border-radius:var(--r-sm); padding:12px 14px; font-size:12px; color:var(--red); line-height:1.6; margin-bottom:22px; font-weight:600; }
.admin-shell .contract-doc h2 { font-size:21px; font-weight:800; margin:0 0 3px; letter-spacing:-0.02em; color:var(--text); }
.admin-shell .contract-blurb { font-size:12.5px; color:var(--muted); line-height:1.55; margin:0 0 18px; }
.admin-shell .contract-intro { font-size:13px; color:var(--text-2); line-height:1.65; margin:0 0 22px; padding-bottom:16px; border-bottom:1px solid var(--border); }
.admin-shell .contract-clause { margin-bottom:16px; }
.admin-shell .contract-clause h3 { font-size:13px; font-weight:700; color:var(--text); margin:0 0 4px; }
.admin-shell .contract-clause p { font-size:13px; color:var(--text-2); line-height:1.7; margin:0; }
.admin-shell .contract-sigs { margin-top:34px; display:flex; gap:44px; flex-wrap:wrap; }
.admin-shell .contract-sig { flex:1; min-width:170px; }
.admin-shell .contract-sig-line { border-top:1px solid var(--text); margin-top:36px; padding-top:5px; font-size:11px; color:var(--muted); text-transform:uppercase; letter-spacing:0.06em; }
.admin-shell .contract-foot { margin-top:30px; padding-top:14px; border-top:1px solid var(--border); font-size:11px; color:var(--muted); line-height:1.6; }
@media print {
  .admin-shell { padding:0; max-width:none; background:#fff; }
  .no-print { display:none !important; }
  .admin-shell .contract-doc { border:none; padding:0; max-width:none; }
}
`;

interface Props {
  params: Promise<{ id: string; type: string }>;
}

export async function generateMetadata({ params }: Props) {
  const { type } = await params;
  return {
    title: `${contractTypeName(type) || "Contract"} — Day14 Realty`,
    robots: { index: false, follow: false },
  };
}

export default async function ContractPage({ params }: Props) {
  const { id, type } = await params;
  const ops = await loadTenantOps("day14-realty");
  const properties = (ops.properties || []) as unknown as REProperty[];
  const property = properties.find((p) => p.id === id);
  const evaluation: REEvaluation | undefined = (ops.evaluations || []).find(
    (e) => e.property_id === id
  );
  if (!property || !evaluation) notFound();
  const contract = buildContract(type, property, evaluation);
  if (!contract) notFound();

  return (
    <div className="admin-shell">
      <style dangerouslySetInnerHTML={{ __html: ADMIN_CSS + CONTRACT_CSS }} />
      <div className="no-print">
        <AdminNav active="realty" />
        <div className="crumb">
          <Link href="/admin/realty">Realty</Link> &nbsp;/&nbsp;{" "}
          <Link href={`/admin/realty/${encodeURIComponent(id)}`}>
            {property.address || "Property"}
          </Link>{" "}
          &nbsp;/&nbsp; {contract.title}
        </div>
        <div className="contract-toolbar">
          <PrintButton />
          <span style={{ fontSize: 12, color: "var(--muted)" }}>
            Review every bracketed term, then send this to your attorney or title company.
          </span>
        </div>
      </div>

      <div className="contract-doc">
        <div className="contract-notice">{CONTRACT_LEGAL_NOTICE}</div>
        <h2>{contract.title}</h2>
        <p className="contract-blurb">{contract.blurb}</p>
        <p className="contract-intro">{contract.intro}</p>
        {contract.clauses.map((c, i) => (
          <div key={i} className="contract-clause">
            <h3>{c.heading}</h3>
            <p>{c.body}</p>
          </div>
        ))}
        <div className="contract-sigs">
          {contract.signatures.map((s, i) => (
            <div key={i} className="contract-sig">
              <div className="contract-sig-line">{s}</div>
            </div>
          ))}
        </div>
        <div className="contract-foot">
          Generated by Day14 Realty from county property data on{" "}
          {new Date().toLocaleDateString()} for {property.address || "this property"} (parcel{" "}
          {property.id}). This is a draft for attorney review — not a finished contract and not
          legal advice.
        </div>
      </div>
    </div>
  );
}
