/**
 * BrandStorefront — generic per-tenant storefront component.
 *
 * Pulls products live from Printify and the tenant's constitution from disk.
 * Renders a minimal, voice-aware brand page at day14.us/brands/[slug].
 *
 * Used by src/app/brands/[slug]/page.tsx auto-generated by new-store-bootstrap.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { existsSync } from "node:fs";
import { homedir } from "node:os";

interface PrintifyProduct {
  id: string;
  title: string;
  description?: string;
  visible?: boolean;
  images?: Array<{ src: string }>;
  variants?: Array<{ price: number; is_enabled: boolean }>;
}

interface Props {
  tenantSlug: string;
  displayName: string;
  niche: string;
}

async function fetchProducts(): Promise<PrintifyProduct[]> {
  const apiKey = process.env.PRINTIFY_API_KEY;
  if (!apiKey) return [];

  try {
    const shopsRes = await fetch("https://api.printify.com/v1/shops.json", {
      headers: { Authorization: `Bearer ${apiKey}` },
      next: { revalidate: 300 }, // 5min cache
    });
    if (!shopsRes.ok) return [];
    const shops = (await shopsRes.json()) as Array<{ id: number }>;
    if (!shops.length) return [];

    const res = await fetch(
      `https://api.printify.com/v1/shops/${shops[0]!.id}/products.json?limit=50`,
      {
        headers: { Authorization: `Bearer ${apiKey}` },
        next: { revalidate: 300 },
      }
    );
    if (!res.ok) return [];
    const data = (await res.json()) as { data?: PrintifyProduct[] };
    return (data.data || []).filter((p) => p.visible !== false);
  } catch {
    return [];
  }
}

async function loadTagline(slug: string): Promise<string | null> {
  const constPath = path.join(homedir(), "Documents/businesses", slug, "CONSTITUTION.md");
  if (!existsSync(constPath)) return null;
  const text = await fs.readFile(constPath, "utf8");
  // The "What this business is" section is usually the second paragraph
  const match = text.match(/## What this business is\s*\n+([^\n]+)/);
  if (match?.[1]) return match[1].trim();
  return null;
}

function minPriceCents(product: PrintifyProduct): number | null {
  if (!product.variants) return null;
  const enabled = product.variants.filter((v) => v.is_enabled);
  if (!enabled.length) return null;
  return Math.min(...enabled.map((v) => v.price));
}

export async function BrandStorefront({ tenantSlug, displayName, niche }: Props) {
  const [products, tagline] = await Promise.all([fetchProducts(), loadTagline(tenantSlug)]);

  return (
    <div
      style={{
        maxWidth: "1100px",
        margin: "0 auto",
        padding: "48px 24px",
        font: '15px/1.5 -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
        color: "#2F2A33",
      }}
    >
      <header style={{ marginBottom: "48px", textAlign: "center" }}>
        <h1 style={{ fontSize: "42px", letterSpacing: "-0.02em", margin: "0 0 12px" }}>
          {displayName}
        </h1>
        <p style={{ color: "#7A6F8F", fontSize: "16px", maxWidth: "640px", margin: "0 auto" }}>
          {tagline || niche}
        </p>
      </header>

      {products.length === 0 ? (
        <div style={{ textAlign: "center", color: "#999", padding: "64px 0" }}>
          <p>New drops landing soon.</p>
          <form
            action={`/api/brands/${tenantSlug}/subscribe`}
            method="POST"
            style={{ marginTop: "24px" }}
          >
            <input
              type="email"
              name="email"
              placeholder="you@email.com"
              required
              style={{
                padding: "12px 16px",
                border: "1px solid #E5DDD0",
                borderRadius: "6px",
                fontSize: "15px",
                width: "240px",
                marginRight: "8px",
              }}
            />
            <button
              type="submit"
              style={{
                padding: "12px 20px",
                background: "#2F2A33",
                color: "white",
                border: "none",
                borderRadius: "6px",
                fontSize: "15px",
                cursor: "pointer",
              }}
            >
              Notify me
            </button>
          </form>
        </div>
      ) : (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
            gap: "32px",
          }}
        >
          {products.map((p) => {
            const price = minPriceCents(p);
            const imgSrc = p.images?.[0]?.src;
            return (
              <article
                key={p.id}
                style={{
                  background: "white",
                  border: "1px solid #E5DDD0",
                  borderRadius: "12px",
                  overflow: "hidden",
                }}
              >
                {imgSrc && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={imgSrc}
                    alt={p.title}
                    style={{ width: "100%", aspectRatio: "1/1", objectFit: "cover", display: "block" }}
                  />
                )}
                <div style={{ padding: "20px" }}>
                  <h2 style={{ fontSize: "16px", margin: "0 0 8px", letterSpacing: "-0.01em" }}>
                    {p.title}
                  </h2>
                  {price !== null && (
                    <div style={{ color: "#7A6F8F", fontSize: "15px", marginBottom: "12px" }}>
                      ${(price / 100).toFixed(2)}
                    </div>
                  )}
                  <a
                    href={`https://printify.com/app/products/${p.id}`}
                    style={{
                      display: "inline-block",
                      padding: "8px 16px",
                      background: "#2F2A33",
                      color: "white",
                      textDecoration: "none",
                      borderRadius: "6px",
                      fontSize: "13px",
                    }}
                  >
                    View product
                  </a>
                </div>
              </article>
            );
          })}
        </div>
      )}

      <footer style={{ marginTop: "80px", textAlign: "center", color: "#999", fontSize: "13px" }}>
        <p>Part of the Day14 family.</p>
      </footer>
    </div>
  );
}
