#!/usr/bin/env node
/**
 * growth-watcher.mjs
 *
 * Day14 OS — self-expanding skill system, always-on mode.
 *
 * Long-running daemon that:
 *   1. Polls the work-register every 5 min
 *   2. Detects patterns: ad-hoc actions repeating 2+ times across distinct contexts
 *   3. Auto-drafts a SKILL.md to seeds/skills/_drafts/{name}/
 *   4. Logs the proposal to growth-log.md
 *   5. Queues a Telegram approval card for Jack
 *
 * Growth-always-on default: 2-occurrence rule (relaxed from skill-promotion-criteria's 3).
 *
 * Run: node ~/Documents/studio/scripts/growth-watcher.mjs
 * Or install as LaunchAgent: bash scripts/install-growth-watcher.sh
 */

import fs from "node:fs/promises";
import path from "node:path";
import { existsSync } from "node:fs";
import { homedir } from "node:os";

// ---- paths ----
const SHARED_DIR = path.join(homedir(), "Documents/businesses/_shared");
const GROWTH_DIR = path.join(SHARED_DIR, "growth");
const REGISTER_PATH = path.join(GROWTH_DIR, "work-register.jsonl");
const GROWTH_LOG = path.join(GROWTH_DIR, "growth-log.md");
const DRAFTS_DIR = path.join(
  homedir(),
  "Documents/studio/docs/seeds/skills/_drafts"
);
const META_DRAFTS_DIR = path.join(
  homedir(),
  "Documents/studio/docs/seeds/skills/_drafts/_meta"
);
const META_GAPS_LOG = path.join(
  homedir(),
  "Documents/businesses/_shared/growth/meta-gaps.md"
);
const META_CIRCUIT_FILE = path.join(
  homedir(),
  "Documents/businesses/_shared/growth/meta-circuit-state.json"
);
const POLLER_DIR = path.join(SHARED_DIR, "poller");
const HEARTBEAT_FILE = path.join(POLLER_DIR, "growth-watcher-heartbeat.log");
const SEEN_FILE = path.join(GROWTH_DIR, "growth-watcher-seen.json");
const TELEGRAM_OUTBOX = path.join(SHARED_DIR, "telegram/outbox");
const ENV_FILE = path.join(homedir(), "Documents/studio/.env.local");

const POLL_INTERVAL_MS = 5 * 60_000; // every 5 min
const HEARTBEAT_INTERVAL_MS = 60_000;

// ---- env ----
async function loadEnv() {
  if (!existsSync(ENV_FILE)) return {};
  const text = await fs.readFile(ENV_FILE, "utf8");
  const env = {};
  for (const line of text.split("\n")) {
    const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.*)\s*$/);
    if (m && !line.trim().startsWith("#")) {
      env[m[1]] = m[2].replace(/^['"]|['"]$/g, "");
    }
  }
  return env;
}

// ---- logging ----
async function log(msg) {
  const stamp = new Date().toISOString();
  const line = `[${stamp}] ${msg}\n`;
  process.stdout.write(line);
  await fs.appendFile(path.join(POLLER_DIR, "growth-watcher.log"), line);
}

async function heartbeat() {
  await fs.appendFile(
    HEARTBEAT_FILE,
    `${new Date().toISOString()} alive\n`
  );
}

// ---- ensure dirs ----
async function ensureDirs() {
  for (const d of [
    GROWTH_DIR,
    DRAFTS_DIR,
    META_DRAFTS_DIR,
    POLLER_DIR,
    TELEGRAM_OUTBOX,
  ]) {
    await fs.mkdir(d, { recursive: true });
  }
  if (!existsSync(REGISTER_PATH)) {
    await fs.writeFile(REGISTER_PATH, "", "utf8");
  }
  if (!existsSync(GROWTH_LOG)) {
    await fs.writeFile(
      GROWTH_LOG,
      "# Growth log\n\n> Auto-generated by growth-watcher.\n> Every detected pattern gets a row.\n\n",
      "utf8"
    );
  }
  if (!existsSync(META_GAPS_LOG)) {
    await fs.writeFile(
      META_GAPS_LOG,
      "# Meta-gaps log\n\n> Auto-generated by growth-watcher (recursive layer).\n> Patterns detected inside the growth cluster itself.\n\n",
      "utf8"
    );
  }
  if (!existsSync(META_CIRCUIT_FILE)) {
    await fs.writeFile(
      META_CIRCUIT_FILE,
      JSON.stringify(
        { open: false, since: null, reason: null, drafts_in_flight: 0 },
        null,
        2
      ),
      "utf8"
    );
  }
}

// ---- throttle: read circuit breaker state ----
async function readMetaCircuit() {
  try {
    return JSON.parse(await fs.readFile(META_CIRCUIT_FILE, "utf8"));
  } catch {
    return { open: false, since: null, reason: null, drafts_in_flight: 0 };
  }
}

async function writeMetaCircuit(state) {
  await fs.writeFile(META_CIRCUIT_FILE, JSON.stringify(state, null, 2), "utf8");
}

// ---- count meta-drafts currently in flight ----
async function countMetaDraftsInFlight() {
  try {
    const entries = await fs.readdir(META_DRAFTS_DIR);
    let count = 0;
    for (const e of entries) {
      const p = path.join(META_DRAFTS_DIR, e, "SKILL.md");
      if (existsSync(p)) count += 1;
    }
    return count;
  } catch {
    return 0;
  }
}

// ---- throttle gate: returns {allow, reason} ----
async function throttleAllowMetaDraft() {
  const state = await readMetaCircuit();
  if (state.open) {
    return { allow: false, reason: `circuit_open: ${state.reason || "unknown"}` };
  }
  const inFlight = await countMetaDraftsInFlight();
  if (inFlight >= 3) {
    return { allow: false, reason: `queue_full: ${inFlight} drafts in flight` };
  }
  return { allow: true, reason: null };
}

// ---- seen state ----
async function loadSeen() {
  if (!existsSync(SEEN_FILE)) return { proposed_phrases: [] };
  try {
    return JSON.parse(await fs.readFile(SEEN_FILE, "utf8"));
  } catch {
    return { proposed_phrases: [] };
  }
}

async function saveSeen(seen) {
  await fs.writeFile(SEEN_FILE, JSON.stringify(seen, null, 2), "utf8");
}

// ---- read register ----
async function readRegister() {
  const text = await fs.readFile(REGISTER_PATH, "utf8");
  return text
    .split("\n")
    .filter((l) => l.trim())
    .map((l) => {
      try {
        return JSON.parse(l);
      } catch {
        return null;
      }
    })
    .filter(Boolean);
}

// ---- normalize phrase for matching ----
function normalizePhrase(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

// ---- group by normalized action ----
// `metaMode`: when true, only consider is_meta=true entries (and inverse otherwise)
function groupAdHocByPhrase(entries, metaMode = false) {
  const groups = new Map();
  for (const entry of entries) {
    if (!entry.is_ad_hoc) continue;
    if (entry.invoked_skill) continue; // skill exists already
    const entryIsMeta = entry.is_meta === true;
    if (metaMode && !entryIsMeta) continue;
    if (!metaMode && entryIsMeta) continue;
    const key = normalizePhrase(entry.action_phrase || "");
    if (!key) continue;
    if (!groups.has(key)) {
      groups.set(key, {
        phrase: entry.action_phrase,
        occurrences: [],
      });
    }
    groups.get(key).occurrences.push(entry);
  }
  return groups;
}

// ---- detect promotion candidates ----
// `minOccurrences` defaults to 2 (domain) — pass 3 for meta layer.
function detectCandidates(groups, seenPhrases, minOccurrences = 2) {
  const candidates = [];
  for (const [normalized, group] of groups) {
    if (seenPhrases.includes(normalized)) continue;
    if (group.occurrences.length < minOccurrences) continue;

    // Require distinct contexts (not N ad-hocs in the same session)
    const distinctContexts = new Set(
      group.occurrences.map((o) => o.context || "default")
    );
    if (distinctContexts.size < minOccurrences) continue;

    candidates.push({
      normalized,
      phrase: group.phrase,
      occurrences: group.occurrences,
      contexts: Array.from(distinctContexts),
    });
  }
  return candidates;
}

// ---- generate a skill name from a phrase ----
function generateSkillName(phrase) {
  return phrase
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .split(/\s+/)
    .slice(0, 4) // first 4 words
    .filter(Boolean)
    .join("-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}

// ---- draft a SKILL.md ----
function draftSkillMd(candidate) {
  const name = generateSkillName(candidate.phrase);
  const triggers = [
    candidate.phrase.toLowerCase(),
    candidate.normalized,
    candidate.phrase.split(" ").slice(0, 2).join(" "),
  ];

  const evidenceLines = candidate.occurrences
    .slice(0, 5)
    .map(
      (o) =>
        `- ${o.timestamp} — context: ${o.context}${o.notes ? ` — ${o.notes}` : ""}`
    )
    .join("\n");

  return `---
name: ${name}
description: AUTO-DRAFT (growth-watcher). ${candidate.phrase}. Promoted after ${candidate.occurrences.length} ad-hoc occurrences across ${candidate.contexts.length} distinct contexts. Needs Jack's review + refinement before promotion to _shared/.
triggers:
${triggers.map((t) => `  - "${t.replace(/"/g, '\\"')}"`).join("\n")}
status: draft
auto_generated_at: ${new Date().toISOString()}
---

# ${name}

> AUTO-DRAFT — growth-watcher detected this as a recurring ad-hoc
> pattern across ${candidate.contexts.length} contexts. Refine before promoting.

## Why this skill exists (auto-generated)

Action phrase observed: "${candidate.phrase}"

The agent did this work ${candidate.occurrences.length} times without an existing skill backing it.
Across these contexts:

${candidate.contexts.map((c) => `- ${c}`).join("\n")}

## Evidence

${evidenceLines}

## Proposed protocol (Jack to fill)

\`\`\`
TODO: Describe what the skill should do, in 1-3 steps.
\`\`\`

## Inputs (Jack to fill)

\`\`\`
TODO: What inputs does the skill take?
\`\`\`

## Hard rules (Jack to fill)

\`\`\`
TODO: What constraints / non-negotiables apply?
\`\`\`

## When invoked (Jack to fill)

\`\`\`
TODO: When should this skill fire vs not fire?
\`\`\`

## Logging

\`[YYYY-MM-DD HH:MM ET] ${name} → outcome: {what}\`

## Promote checklist (before moving to _shared/skills/)

- [ ] Reviewed evidence (above)
- [ ] Filled the TODO sections
- [ ] Confirmed naming via skill-naming-validator
- [ ] Added to bootstrap-day14-os.sh skills loop
- [ ] Moved file from _drafts/ to seeds/skills/${name}/SKILL.md
- [ ] Committed
`;
}

// ---- escape MarkdownV2 for Telegram ----
function escapeMd(text) {
  return String(text).replace(/([_*[\]()~`>#+\-=|{}.!\\])/g, "\\$1");
}

// ---- queue Telegram approval card ----
async function queueTelegramApproval(candidate, draftName) {
  const env = await loadEnv();
  const chatId = env.TELEGRAM_CHAT_ID;
  if (!chatId) return; // Telegram not wired yet — silently skip

  const filename = `${Date.now()}-growth-${draftName}.json`;
  const filepath = path.join(TELEGRAM_OUTBOX, filename);

  const text =
    `🌱 *Growth\\-watcher: new skill candidate*\n\n` +
    `Action observed ${candidate.occurrences.length}× across ${candidate.contexts.length} contexts:\n` +
    `_${escapeMd(candidate.phrase.slice(0, 80))}_\n\n` +
    `Draft: \`${escapeMd(draftName)}\`\n` +
    `Location: \`_drafts/${escapeMd(draftName)}/SKILL\\.md\`\n\n` +
    `Review + promote when ready\\.`;

  await fs.writeFile(
    filepath,
    JSON.stringify(
      {
        chat_id: chatId,
        text,
        parse_mode: "MarkdownV2",
        urgency: "P3",
        queued_at: new Date().toISOString(),
        sent_at: null,
      },
      null,
      2
    )
  );
}

// ---- append to growth log ----
async function appendGrowthLog(candidate, draftName) {
  const line = `\n## ${new Date().toISOString()} — \`${draftName}\`\n\n- Phrase: ${candidate.phrase}\n- Occurrences: ${candidate.occurrences.length}\n- Contexts: ${candidate.contexts.length} (${candidate.contexts.join(", ")})\n- Draft: \`docs/seeds/skills/_drafts/${draftName}/SKILL.md\`\n- Status: pending Jack's review\n`;
  await fs.appendFile(GROWTH_LOG, line, "utf8");
}

// ---- append to meta-gaps log (recursive layer) ----
async function appendMetaGapsLog(candidate, draftName, risk) {
  const line = `\n## ${new Date().toISOString()} — \`${draftName}\` (meta)\n\n- Phrase: ${candidate.phrase}\n- Occurrences: ${candidate.occurrences.length}\n- Growth-cluster contexts: ${candidate.contexts.length} (${candidate.contexts.join(", ")})\n- Recurrence risk: ${risk.toFixed(2)}\n- Draft: \`docs/seeds/skills/_drafts/_meta/${draftName}/SKILL.md\`\n- Status: pending Jack's review (P2 — meta layer)\n`;
  await fs.appendFile(META_GAPS_LOG, line, "utf8");
}

// ---- queue Telegram approval for a META draft (P2, distinct copy) ----
async function queueTelegramApprovalMeta(candidate, draftName, risk) {
  const env = await loadEnv();
  const chatId = env.TELEGRAM_CHAT_ID;
  if (!chatId) return;

  const filename = `${Date.now()}-meta-growth-${draftName}.json`;
  const filepath = path.join(TELEGRAM_OUTBOX, filename);

  const riskBadge =
    risk < 0.3 ? "🟢" : risk < 0.5 ? "🟡" : risk < 0.7 ? "🟠" : "🔴";

  const text =
    `🧬 *Meta\\-growth: skill candidate from inside the growth cluster*\n\n` +
    `${riskBadge} Recurrence risk: ${escapeMd(risk.toFixed(2))}\n` +
    `Pattern observed ${candidate.occurrences.length}× across ${candidate.contexts.length} growth components:\n` +
    `_${escapeMd(candidate.phrase.slice(0, 80))}_\n\n` +
    `Draft: \`${escapeMd(draftName)}\`\n` +
    `Location: \`_drafts/_meta/${escapeMd(draftName)}/SKILL\\.md\`\n\n` +
    (risk >= 0.7
      ? `⚠️ HIGH risk — Jack classifies before promote\\.`
      : `Review carefully — meta\\-skills shape architecture\\.`);

  await fs.writeFile(
    filepath,
    JSON.stringify(
      {
        chat_id: chatId,
        text,
        parse_mode: "MarkdownV2",
        urgency: "P2", // meta layer = more visible than domain P3
        queued_at: new Date().toISOString(),
        sent_at: null,
      },
      null,
      2
    )
  );
}

// ---- compute recurrence_risk (mirror of draftMetaSkillMd's logic) ----
function computeRecurrenceRisk(phrase) {
  const text = phrase.toLowerCase();
  let risk = 0.1;
  if (text.includes("skill") || text.includes("draft")) risk += 0.3;
  if (text.includes("watcher") || text.includes("growth")) risk += 0.2;
  if (text.includes("rule") || text.includes("threshold")) risk += 0.2;
  return Math.min(1.0, risk);
}

// ---- write the draft file ----
async function writeDraft(candidate, options = {}) {
  const isMeta = options.isMeta === true;
  const name = generateSkillName(candidate.phrase);
  if (!name || name.length < 3) {
    await log(`Skipping candidate with too-short name: "${candidate.phrase}"`);
    return null;
  }

  const targetDir = isMeta ? META_DRAFTS_DIR : DRAFTS_DIR;
  const draftDir = path.join(targetDir, name);
  const draftPath = path.join(draftDir, "SKILL.md");

  if (existsSync(draftPath)) {
    await log(`Draft already exists for "${name}" (meta=${isMeta}), skipping`);
    return null;
  }

  await fs.mkdir(draftDir, { recursive: true });
  const content = isMeta
    ? draftMetaSkillMd(candidate)
    : draftSkillMd(candidate);
  await fs.writeFile(draftPath, content, "utf8");

  return name;
}

// ---- meta-skill template (separate from domain) ----
function draftMetaSkillMd(candidate) {
  const name = generateSkillName(candidate.phrase);
  const triggers = [
    candidate.phrase.toLowerCase(),
    candidate.normalized,
    `meta: ${candidate.phrase.split(" ").slice(0, 2).join(" ")}`,
  ];

  // Heuristic recurrence_risk: higher if phrase mentions other growth-cluster ops
  const text = candidate.phrase.toLowerCase();
  let risk = 0.1;
  if (text.includes("skill") || text.includes("draft")) risk += 0.3;
  if (text.includes("watcher") || text.includes("growth")) risk += 0.2;
  if (text.includes("rule") || text.includes("threshold")) risk += 0.2;
  risk = Math.min(1.0, risk);

  const evidenceLines = candidate.occurrences
    .slice(0, 5)
    .map(
      (o) =>
        `- ${o.timestamp} — component: ${o.context}${o.notes ? ` — ${o.notes}` : ""}`
    )
    .join("\n");

  return `---
name: ${name}
description: META-DRAFT (growth-watcher, recursive layer). ${candidate.phrase}. Detected after ${candidate.occurrences.length} occurrences across ${candidate.contexts.length} growth-cluster components.
pack: meta-growth
parent_anchor: growth-always-on
is_meta: true
recurrence_risk: ${risk.toFixed(2)}
triggers:
${triggers.map((t) => `  - "${t.replace(/"/g, '\\"')}"`).join("\n")}
status: meta-draft
auto_generated_at: ${new Date().toISOString()}
---

# ${name}

> META-DRAFT — recursive-growth-watcher detected this as a pattern in
> the growth cluster itself. Read carefully before promoting; meta-skills
> shape the empire's growth architecture.

## Why this meta-skill exists (auto-generated)

Pattern observed: "${candidate.phrase}"

Detected ${candidate.occurrences.length} times across these growth-cluster components:

${candidate.contexts.map((c) => `- ${c}`).join("\n")}

## Recurrence risk: ${risk.toFixed(2)}

${risk < 0.3 ? "Low — this skill mostly observes/logs; safe to promote." : risk < 0.5 ? "Medium — visible Telegram notification recommended." : risk < 0.7 ? "Elevated — Council review recommended before promotion." : "HIGH — Jack must classify before draft promotes. May spawn more meta-skills."}

## Evidence

${evidenceLines}

## Proposed protocol (Jack to fill)

\`\`\`
TODO: Describe what this meta-skill should do, in 1-3 steps.
Reference which growth-cluster components it interacts with.
\`\`\`

## Infrastructure dependencies (Jack to fill)

\`\`\`
TODO: Which growth-cluster components must exist for this to function?
\`\`\`

## Recursion guard (Jack to fill)

\`\`\`
TODO: How does this skill prevent itself from spawning runaway sub-skills?
\`\`\`

## Sample meta-patterns this catches (Jack to fill)

\`\`\`
TODO: 2-3 concrete examples of growth-system patterns that would trigger this.
\`\`\`

## Hard rules (Jack to fill)

\`\`\`
TODO: Constraints. Always include "never modify its own throttle" if applicable.
\`\`\`

## Promote checklist (before moving to _shared/skills/)

- [ ] Reviewed evidence (above)
- [ ] Filled the TODO sections
- [ ] Confirmed naming via skill-naming-validator
- [ ] Recurrence_risk classification is correct
- [ ] Added to bootstrap-day14-os.sh skills loop
- [ ] Moved file from _drafts/_meta/ to seeds/skills/${name}/SKILL.md
- [ ] Committed
- [ ] If risk > 0.5: Council reviewed

## Logging

\`[YYYY-MM-DD HH:MM ET] ${name} → outcome: {what}\`
`;
}

// ---- main loop ----
async function scanCycle() {
  try {
    const seen = await loadSeen();
    const entries = await readRegister();

    if (entries.length === 0) return;

    // ---- PASS 1: domain (is_meta=false), 2-occurrence rule ----
    const domainGroups = groupAdHocByPhrase(entries, false);
    const domainCandidates = detectCandidates(
      domainGroups,
      seen.proposed_phrases,
      2
    );

    if (domainCandidates.length > 0) {
      await log(`Domain pass: ${domainCandidates.length} candidate(s)`);
      for (const candidate of domainCandidates) {
        const draftName = await writeDraft(candidate);
        if (!draftName) continue;

        await appendGrowthLog(candidate, draftName);
        await queueTelegramApproval(candidate, draftName);
        seen.proposed_phrases.push(candidate.normalized);

        await log(`Drafted domain candidate: ${draftName}`);
      }
    }

    // ---- PASS 2: meta (is_meta=true), 3-occurrence rule, throttled ----
    const metaGroups = groupAdHocByPhrase(entries, true);
    const metaCandidates = detectCandidates(
      metaGroups,
      seen.proposed_phrases,
      3
    );

    if (metaCandidates.length > 0) {
      await log(`Meta pass: ${metaCandidates.length} candidate(s) detected`);

      for (const candidate of metaCandidates) {
        // Throttle gate — caps + circuit breaker
        const gate = await throttleAllowMetaDraft();
        if (!gate.allow) {
          await log(
            `🔴 meta-draft BLOCKED by throttle (${gate.reason}) — phrase: "${candidate.phrase}"`
          );
          // Don't add to seen — we want to retry once the throttle re-opens
          continue;
        }

        const risk = computeRecurrenceRisk(candidate.phrase);

        // recurrence_risk > 0.7 → block automatic draft; surface only
        if (risk > 0.7) {
          await log(
            `🔴 meta-draft GATED — risk ${risk.toFixed(2)} > 0.7 for "${candidate.phrase}". Surfacing to Jack without auto-drafting.`
          );
          await appendMetaGapsLog(candidate, "(gated, no draft)", risk);
          // Still notify, but as a gated alert
          await queueTelegramApprovalMeta(candidate, "(gated)", risk);
          seen.proposed_phrases.push(candidate.normalized);
          continue;
        }

        const draftName = await writeDraft(candidate, { isMeta: true });
        if (!draftName) continue;

        await appendMetaGapsLog(candidate, draftName, risk);
        await queueTelegramApprovalMeta(candidate, draftName, risk);
        seen.proposed_phrases.push(candidate.normalized);

        await log(
          `Drafted meta candidate: ${draftName} (risk=${risk.toFixed(2)})`
        );
      }
    }

    await saveSeen(seen);
  } catch (err) {
    await log(`scanCycle error: ${err.message}`);
  }
}

// ---- main ----
async function main() {
  await ensureDirs();
  await log(`Growth-watcher starting (poll ${POLL_INTERVAL_MS / 1000}s)`);
  await log(`Register: ${REGISTER_PATH}`);
  await log(`Drafts:   ${DRAFTS_DIR}`);

  await log(`Meta-drafts: ${META_DRAFTS_DIR}`);
  await log(`Circuit: ${META_CIRCUIT_FILE}`);

  setInterval(scanCycle, POLL_INTERVAL_MS);
  setInterval(heartbeat, HEARTBEAT_INTERVAL_MS);

  await scanCycle();
  await heartbeat();

  await log("Growth-watcher running (domain + meta passes active).");
}

main().catch(async (err) => {
  await log(`FATAL: ${err.message}`);
  process.exit(1);
});
